import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Vec3, Quat } from "../schemas.js";

export const animationTool: ToolDef = categoryTool(
  "animation",
  "Animation assets, skeletons, montages, blendspaces, anim blueprints, physics assets.",
  {
    read_anim_blueprint:  bp("Read AnimBP structure. Params: assetPath", "read_anim_blueprint"),
    read_montage:         bp("Read montage. Params: assetPath", "read_anim_montage", (p) => ({ assetPath: p.assetPath })),
    read_sequence:        bp("Read anim sequence. Params: assetPath", "read_anim_sequence", (p) => ({ assetPath: p.assetPath })),
    scan_animation_tracks: bp("Scan AnimSequence bone-track counts. Params: directory?, recursive?, assetPaths?, skeletonPath?, targetTrackCount?, includeTrackNames?", "scan_animation_tracks"),
    read_blendspace:      bp("Read blendspace. Params: assetPath", "read_blendspace", (p) => ({ assetPath: p.assetPath })),
    add_blend_sample:     bp("Append a sample to a BlendSpace. Params: assetPath, animation (AnimSequence path), position {x,y} (or flat x,y) (#248)", "add_blend_sample", (p) => ({ assetPath: p.assetPath, animation: p.animation, position: p.position, x: p.x, y: p.y })),
    set_blend_sample:     bp("Move an existing BlendSpace sample or swap its animation. Params: assetPath, sampleIndex, position? {x,y} (or flat x,y), animation? (#272)", "set_blend_sample", (p) => ({ assetPath: p.assetPath, sampleIndex: p.sampleIndex, position: p.position, x: p.x, y: p.y, animation: p.animation })),
    list:                 bp("List anim assets. Params: directory?, recursive?", "list_anim_assets"),
    create_montage:       bp("Create montage. Params: animSequencePath, name?, packagePath?", "create_anim_montage"),
    create_anim_blueprint: bp("Create AnimBP. Params: skeletonPath, name?, packagePath?, parentClass?", "create_anim_blueprint"),
    create_blendspace:    bp("Create blendspace (2D). Params: skeletonPath, name?, packagePath?, axisHorizontal?, axisVertical?", "create_blendspace"),
    create_blendspace_1d: bp("Create BlendSpace1D. Params: skeletonPath, name?, packagePath?, axisName? (default Speed), axisMin?, axisMax?, gridNum? (#459)", "create_blendspace_1d", (p) => ({ name: p.name, skeletonPath: p.skeletonPath, packagePath: p.packagePath, axisName: p.axisName, axisMin: p.axisMin, axisMax: p.axisMax, gridNum: p.gridNum, onConflict: p.onConflict })),
    populate_blendspace:  bp("One-call axis params + samples authoring for BlendSpace 1D/2D. Params: assetPath, axis? ({name?, min?, max?, gridNum?}) for axis 0, blendspaceAxes? (per-axis array), axisHorizontal?/axisVertical? + horizontalMin/horizontalMax/verticalMin/verticalMax/gridNumHorizontal/gridNumVertical (back-compat), samples ([{animationPath, x, y?}]), clearExisting? (default true) (#459)", "populate_blendspace", (p) => ({ assetPath: p.assetPath, axis: p.axis, axes: p.blendspaceAxes, axisIndex: p.axisIndex, axisHorizontal: p.axisHorizontal, axisVertical: p.axisVertical, horizontalMin: p.horizontalMin, horizontalMax: p.horizontalMax, verticalMin: p.verticalMin, verticalMax: p.verticalMax, gridNumHorizontal: p.gridNumHorizontal, gridNumVertical: p.gridNumVertical, samples: p.samples, clearExisting: p.clearExisting })),
    add_notify:           bp("Add notify. For PlayMontageNotify the notifyName is also written onto the spawned notify object so OnPlayMontageNotifyBegin broadcasts it (not 'None'), and montage branching-point markers refresh (#528). Params: assetPath, notifyName, triggerTime, notifyClass?", "add_anim_notify"),
    remove_notify:        bp("Remove notify(s) by name and/or class. Pass at least one of notifyName/notifyClass; both filters AND. Idempotent: alreadyDeleted=true if no match. Params: assetPath, notifyName?, notifyClass? (#471)", "remove_anim_notify", (p) => ({ assetPath: p.assetPath, notifyName: p.notifyName, notifyClass: p.notifyClass })),
    get_skeleton_info:    bp("Read skeleton. Params: assetPath", "get_skeleton_info"),
    list_sockets:         bp("List sockets. Params: assetPath", "list_sockets"),
    list_skeletal_meshes: bp("List skeletal meshes. Params: directory?, recursive?", "list_skeletal_meshes"),
    get_physics_asset:    bp("Read physics asset. Params: assetPath", "get_physics_asset_info"),
    create_sequence:      bp("Create blank AnimSequence. Params: name, skeletonPath, packagePath?, numFrames?, frameRate?", "create_sequence"),
    set_bone_keyframes:   bp("Set bone transform keyframes. Params: assetPath, boneName, keyframes", "set_bone_keyframes"),
    bake_keyframes_batch: bp("Bake per-bone keyframe arrays for many bones into an AnimSequence in one call. Auto-creates each bone track first (set_bone_keyframes silently leaves a T-pose if the track is missing), wraps the batch in one transaction, and raises if any bone fails instead of reporting hollow success (#540). Params: assetPath, tracks ([{bone, keyframes:[{location,rotation{x,y,z,w},scale?}]}]), save? (default true)", "bake_keyframes_batch", (p) => ({ assetPath: p.assetPath, tracks: p.tracks, save: p.save })),
    get_bone_transforms:  bp("Read reference pose transforms. Params: skeletonPath, boneNames?, space? ('local' default, or 'component' for composed parent-chain transforms - retarget-chain / anatomical-scale work) (#245)", "get_bone_transforms"),
    inspect_anim_nodes:   bp("Deep-dump the FAnimNode_* struct of anim graph nodes (PoseDriver PoseTargets/PoseAsset/RBF params/source bones, etc.) that read_anim_graph omits because it skips the 'Node' property. Params: assetPath, graphName? (default AnimGraph), nodeClass? (substring filter, e.g. 'PoseDriver') (#657)", "inspect_anim_nodes", (p) => ({ assetPath: p.assetPath, graphName: p.graphName, nodeClass: p.nodeClass })),
    compare_curves_to_morph_targets: bp("Compare an AnimSequence/PoseAsset's curve names against a SkeletalMesh's morph target names. Returns curves[], morphTargets[], matched[], curvesWithoutMorph[], morphsWithoutCurve[] - verify authored curves drive morphs without Python. Params: animPath (AnimSequence or PoseAsset), skeletalMeshPath (#656)", "compare_curves_to_morph_targets", (p) => ({ animPath: p.animPath, skeletalMeshPath: p.skeletalMeshPath })),
    set_montage_sequence: bp("Replace the animation sequence in a montage slot. With segmentIndex, replaces only that one segment; without it, replaces every segment in the slot. Params: assetPath, animSequencePath, slotIndex? (default 0), segmentIndex? (#626)", "set_montage_sequence", (p) => ({ assetPath: p.assetPath, animSequencePath: p.animSequencePath, slotIndex: p.slotIndex, segmentIndex: p.segmentIndex })),
    set_montage_properties: bp("Set montage properties. Params: assetPath, sequenceLength?, rateScale?, blendIn?, blendOut?", "set_montage_properties"),
    create_state_machine: bp("Create state machine in AnimBP. Params: assetPath, name?, graphName?", "create_state_machine"),
    add_state:            bp("Add state to a state machine. Params: assetPath, stateMachineName, stateName", "add_state"),
    add_transition:       bp("Add directed transition between states. Params: assetPath, stateMachineName, fromState, toState", "add_transition"),
    set_state_animation:  bp("Assign anim asset to state. Params: assetPath, stateMachineName, stateName, animAssetPath", "set_state_animation"),
    set_transition_blend: bp("Set blend type/duration on transition. Params: assetPath, stateMachineName, fromState, toState, blendDuration?, blendLogic?", "set_transition_blend"),
    set_transition_condition: bp("Set a transition's 'can enter transition' condition from a bool variable, keyed by transition (not graph name - every rule graph is named 'Transition' so blueprint graph tools can only reach the first). Wires VariableGet(bool) -> bCanEnterTransition, replacing any prior condition. Identify the transition by transitionGuid (from add_transition/read_state_machine) OR fromState+toState. Params: assetPath, stateMachineName, variableName (existing bool var), transitionGuid? OR fromState?+toState?, negate? (default false) (#707)", "set_transition_condition", (p) => ({ assetPath: p.assetPath, stateMachineName: p.stateMachineName, variableName: p.variableName, transitionGuid: p.transitionGuid, fromState: p.fromState, toState: p.toState, negate: p.negate })),
    read_state_machine:   bp("Read state machine topology. Params: assetPath, stateMachineName", "read_state_machine"),
    read_anim_graph:      bp("Read AnimBP AnimGraph nodes with properties & pins. Params: assetPath, graphName?", "read_anim_graph"),
    add_curve:            bp("Add float curve to AnimSequence. Params: assetPath, curveName, curveType?", "add_curve"),
    set_anim_curve_keys:  bp("Set float-curve key VALUES on an AnimSequence (add_curve only creates an empty named curve - it cannot set keyframe values). Adds the curve if missing, then replaces its keys. Use for authoring Distance/Speed/any float curve directly. Params: assetPath, curveName, keys ([{time, value, interp?('linear'|'constant'|'cubic')}]), interpolation? (default 'linear', applied to keys without their own interp) (#712)", "set_anim_curve_keys", (p) => ({ assetPath: p.assetPath, curveName: p.curveName, keys: p.keys, interpolation: p.interpolation })),
    apply_animation_modifier: bp("Instantiate a UAnimationModifier subclass and run it on an AnimSequence. Headline use: modifierClass='DistanceCurveModifier' bakes a Distance curve from the clip's root motion for distance matching (needs root motion baked first - see bake_root_motion_from_bone). Registers the modifier on the sequence so it re-applies on reimport. props sets the modifier's EditAnywhere fields (e.g. DistanceCurveModifier: {CurveName, Axis:'XY'|'X'|..., bStopAtEnd, StopSpeedThreshold, SampleRate}). Note: DistanceCurveModifier ships in the 'Animation Locomotion Library' plugin (off by default) - enable it first. Params: assetPath, modifierClass (short name or /Script path), props? (#712)", "apply_animation_modifier", (p) => ({ assetPath: p.assetPath, modifierClass: p.modifierClass, props: p.props })),
    set_montage_slot:     bp("Set slot name on a montage track. Params: assetPath, slotName, trackIndex?", "set_montage_slot"),
    add_montage_section:  bp("Add composite section to montage. Params: assetPath, sectionName, startTime?, linkedSection?", "add_montage_section"),
    create_ik_rig:        bp("Create IKRigDefinition asset, optionally with retargetRoot + chains[]. Params: name, skeletalMeshPath, packagePath?, retargetRoot?, chains?: [{name, startBone, endBone, goal?}]", "create_ik_rig"),
    read_ik_rig:          bp("Read IK Rig chains, solvers, skeleton. Params: assetPath", "read_ik_rig"),
    list_control_rig_variables: bp("List ControlRig variables and hierarchy. Params: assetPath", "list_control_rig_variables"),
    read_control_rig_hierarchy: bp("Read a Control Rig's per-element hierarchy metadata: each element's name, type (Bone|Control|Null|Curve...), index, and parent. Params: assetPath (#619)", "read_control_rig_hierarchy", (p) => ({ assetPath: p.assetPath })),
    set_root_motion:    bp("Set root motion settings on AnimSequence. Params: assetPath, enableRootMotion?, forceRootLock?, useNormalizedRootMotionScale?, rootMotionRootLock?", "set_root_motion_settings", (p) => ({ path: p.assetPath, enableRootMotion: p.enableRootMotion, forceRootLock: p.forceRootLock, useNormalizedRootMotionScale: p.useNormalizedRootMotionScale, rootMotionRootLock: p.rootMotionRootLock })),
    add_virtual_bone:   bp("Add virtual bone. Params: skeletonPath, sourceBone, targetBone", "add_virtual_bone"),
    remove_virtual_bone: bp("Remove virtual bone. Params: skeletonPath, virtualBoneName", "remove_virtual_bone"),
    create_composite:   bp("Create AnimComposite. Params: name, skeletonPath, packagePath?", "create_anim_composite"),
    list_modifiers:     bp("List applied animation modifiers. Params: assetPath", "list_anim_modifiers", (p) => ({ path: p.assetPath })),
    create_ik_retargeter: bp("Create IKRetargeter asset and (default) initialize the UE 5.7 ops stack: assigns sourceRig+targetRig to all ops, runs AutoMapChains. Returns chainsMapped count. Params: name, packagePath?, sourceRig?, targetRig?, autoMapChains? (default true) (#246)", "create_ik_retargeter", (p) => ({ name: p.name, packagePath: p.packagePath, sourceRig: p.sourceRig, targetRig: p.targetRig, autoMapChains: p.autoMapChains, onConflict: p.onConflict })),
    read_ik_retargeter: bp("Read IKRetargeter: source/target rigs and chain mappings. Params: assetPath (#246)", "read_ik_retargeter", (p) => ({ assetPath: p.assetPath })),
    set_ik_rig_mesh:      bp("Set the preview/source skeletal mesh on an EXISTING IK Rig. Params: rigPath, meshPath (#701)", "set_ik_rig_mesh", (p) => ({ rigPath: p.rigPath, meshPath: p.meshPath })),
    set_ik_retargeter_rig: bp("Set the source or target IK Rig on an EXISTING IK Retargeter. Params: retargeterPath, rigPath, side? (source|target, default target) (#703)", "set_ik_retargeter_rig", (p) => ({ retargeterPath: p.retargeterPath, rigPath: p.rigPath, side: p.side })),
    auto_align_retarget_pose: bp("Auto-align all bones of the source/target retarget pose (chain-to-chain) - fixes a retargeter that outputs a static reference pose. Params: retargeterPath, side? (source|target, default target) (#701)", "auto_align_retarget_pose", (p) => ({ retargeterPath: p.retargeterPath, side: p.side })),
    reset_retarget_pose:  bp("Reset the current retarget pose (all bones) to the reference pose. Params: retargeterPath, side? (source|target, default target) (#701)", "reset_retarget_pose", (p) => ({ retargeterPath: p.retargeterPath, side: p.side })),
    batch_retarget_animations: bp("Bake a set of source AnimSequences onto the target skeleton through an IK Retargeter (RunBatchRetarget). Params: retargeterPath, sourceMesh, targetMesh, animPaths[], outputPath? (default: alongside source), prefix?, suffix? (default _Retargeted), overwrite? (#701)", "batch_retarget_animations", (p) => ({ retargeterPath: p.retargeterPath, sourceMesh: p.sourceMesh, targetMesh: p.targetMesh, animPaths: p.animPaths, outputPath: p.outputPath, prefix: p.prefix, suffix: p.suffix, overwrite: p.overwrite })),
    set_anim_blueprint_skeleton: bp("Set target skeleton on AnimBP. Params: assetPath, skeletonPath", "set_anim_blueprint_skeleton"),
    read_bone_track:    bp("Read bone transform samples from AnimSequence. Params: assetPath, boneName, frames?: [int]", "read_bone_track"),
    create_pose_search_database: bp("Create a PoseSearchDatabase asset (motion matching). Params: name, packagePath?, schemaPath?", "create_pose_search_database"),
    set_pose_search_schema:      bp("Set the Schema on an existing PoseSearchDatabase. Params: assetPath, schemaPath", "set_pose_search_schema", (p) => ({ assetPath: p.assetPath, schemaPath: p.schemaPath })),
    add_pose_search_sequence:    bp("Append an AnimSequence/AnimComposite/AnimMontage/BlendSpace to a PoseSearchDatabase, with optional per-clip flags. Params: assetPath, sequencePath, mirror? ('original'|'mirrored'|'both'), disableReselection?, sampleStart?, sampleEnd?, enabled? (#684)", "add_pose_search_sequence", (p) => ({ assetPath: p.assetPath, sequencePath: p.sequencePath, mirror: p.mirror, disableReselection: p.disableReselection, sampleStart: p.sampleStart, sampleEnd: p.sampleEnd, enabled: p.enabled })),
    set_pose_search_clips:       bp("Author the whole clip list of a PoseSearchDatabase in one call (the 'duplicate a stock PSD, swap its clips' pipeline step). Replaces the list by default. Each clip carries per-entry flags. Params: assetPath, clips ([{sequencePath, mirror? ('original'|'mirrored'|'both'), disableReselection?, sampleStart?, sampleEnd?, enabled?}] - a bare string path also works), clearExisting? (default true). Follow with build_pose_search_index (#684)", "set_pose_search_clips", (p) => ({ assetPath: p.assetPath, clips: p.clips, clearExisting: p.clearExisting })),
    build_pose_search_index:     bp("Build (or rebuild) the search index. Params: assetPath, wait? (default true)", "build_pose_search_index", (p) => ({ assetPath: p.assetPath, wait: p.wait })),
    read_pose_search_database:   bp("Inspect a PoseSearchDatabase: schema, animation entries, cost biases, tags. Params: assetPath", "read_pose_search_database", (p) => ({ assetPath: p.assetPath })),
    set_pose_search_database_settings: bp("Tune a PoseSearchDatabase: cost biases, KD-tree neighbours, search mode, PCA components, normalization set. Params: assetPath, continuingPoseCostBias?, baseCostBias?, loopingCostBias?, kdTreeQueryNumNeighbors?, numberOfPrincipalComponents?, poseSearchMode? ('bruteforce'|'pcakdtree'|'vptree'|'eventonly'), normalizationSetPath? (motion matching)", "set_pose_search_database_settings", (p) => ({ assetPath: p.assetPath, continuingPoseCostBias: p.continuingPoseCostBias, baseCostBias: p.baseCostBias, loopingCostBias: p.loopingCostBias, kdTreeQueryNumNeighbors: p.kdTreeQueryNumNeighbors, numberOfPrincipalComponents: p.numberOfPrincipalComponents, poseSearchMode: p.poseSearchMode, normalizationSetPath: p.normalizationSetPath })),
    create_pose_search_schema:   bp("Create a PoseSearchSchema (the feature definition a database indexes against). Binds a skeleton (and optional mirror table) and, by default, adds Trajectory+Pose default channels so the schema is immediately buildable. Refine with add_pose_search_schema_*_channel. Params: name, skeletonPath, packagePath?, mirrorDataTablePath?, sampleRate?, addDefaultChannels? (default true) (motion matching)", "create_pose_search_schema", (p) => ({ name: p.name, skeletonPath: p.skeletonPath, packagePath: p.packagePath, mirrorDataTablePath: p.mirrorDataTablePath, sampleRate: p.sampleRate, addDefaultChannels: p.addDefaultChannels, onConflict: p.onConflict })),
    add_pose_search_schema_pose_channel: bp("Add a Pose feature channel to a schema (samples named bones for velocity/position/rotation/phase). Params: schemaPath, bones ([{bone, flags?:['velocity','position','rotation','phase'], weight?}] - a bare bone-name string defaults to position), weight? (motion matching)", "add_pose_search_schema_pose_channel", (p) => ({ schemaPath: p.schemaPath, bones: p.bones, weight: p.weight })),
    add_pose_search_schema_trajectory_channel: bp("Add a Trajectory feature channel to a schema (past/future motion samples). Params: schemaPath, samples ([{offset (seconds; negative=history, positive=prediction), flags?:['position','velocity','facingDirection','velocityDirection', ...XY variants], weight?}]), weight? (motion matching)", "add_pose_search_schema_trajectory_channel", (p) => ({ schemaPath: p.schemaPath, samples: p.samples, weight: p.weight })),
    read_pose_search_schema:     bp("Inspect a PoseSearchSchema: skeleton(s), mirror table, sample rate, feature channels. Params: schemaPath (motion matching)", "read_pose_search_schema", (p) => ({ schemaPath: p.schemaPath })),
    create_mirror_data_table:    bp("Create a MirrorDataTable for a skeleton (needed for mirrored poses in motion matching / mirror nodes). Auto-derives bone-pair rows from find/replace expressions (defaults to UE mannequin _l/_r suffix swap). Params: name, skeletonPath, packagePath?, expressions? ([{find, replace, method?:'suffix'|'prefix'|'regex'}]), mirrorAxis? (motion matching)", "create_mirror_data_table", (p) => ({ name: p.name, skeletonPath: p.skeletonPath, packagePath: p.packagePath, expressions: p.expressions, mirrorAxis: p.mirrorAxis, onConflict: p.onConflict })),
    read_mirror_data_table:      bp("Inspect a MirrorDataTable: skeleton and bone-pair rows (name -> mirroredName). Params: assetPath (motion matching)", "read_mirror_data_table", (p) => ({ assetPath: p.assetPath })),
    create_pose_search_normalization_set: bp("Create a PoseSearchNormalizationSet grouping databases so they normalize their cost space together (consistent blending across a locomotion set). Assign it via set_pose_search_database_settings(normalizationSetPath). Params: name, packagePath?, databases? ([PoseSearchDatabase paths]) (motion matching)", "create_pose_search_normalization_set", (p) => ({ name: p.name, packagePath: p.packagePath, databases: p.databases, onConflict: p.onConflict })),
    add_motion_matching_node:    bp("Add a Motion Matching node to an AnimBP AnimGraph and point it at a PoseSearchDatabase (the runtime node that searches the database each frame). Connects its output to the Output Pose by default. For chooser-driven database selection, bind an anim-node function that calls SetDatabasesToSearch. Params: assetPath (AnimBP), databasePath, graphName? (default AnimGraph), connectToOutput? (default true), blendTime? (motion matching)", "add_motion_matching_node", (p) => ({ assetPath: p.assetPath, databasePath: p.databasePath, graphName: p.graphName, connectToOutput: p.connectToOutput, blendTime: p.blendTime })),
    add_pose_history_node:       bp("Add a Pose History (PoseSearchHistoryCollector) node to an AnimBP AnimGraph - the Motion Matching node needs it in the graph to query pose/trajectory history. Defaults to self-generated trajectory (no external trajectory pin needed) and inserts itself into the pose chain feeding the Output Pose. Params: assetPath (AnimBP), graphName? (default AnimGraph), poseCount?, samplingInterval?, generateTrajectory? (default true), trajectoryHistoryCount?, trajectoryPredictionCount?, insertBeforeOutput? (default true) (motion matching)", "add_pose_history_node", (p) => ({ assetPath: p.assetPath, graphName: p.graphName, poseCount: p.poseCount, samplingInterval: p.samplingInterval, generateTrajectory: p.generateTrajectory, trajectoryHistoryCount: p.trajectoryHistoryCount, trajectoryPredictionCount: p.trajectoryPredictionCount, insertBeforeOutput: p.insertBeforeOutput })),
    set_motion_matching_chooser: bp("Drive the Motion Matching node's Database from a ChooserTable so the database is selected at runtime by character state. Wires a thread-safe EvaluateChooser (result typed to PoseSearchDatabase) into the MM node's Database pin. contextSource selects what the chooser reads its columns from: 'self' (default, the anim instance - choosers branching on AnimBP variables) or 'pawn' (the owning pawn via TryGetPawnOwner - choosers branching on character/pawn state). Params: assetPath (AnimBP), chooserPath (ChooserTable), graphName? (default AnimGraph), contextSource? ('self'|'pawn') (motion matching)", "set_motion_matching_chooser", (p) => ({ assetPath: p.assetPath, chooserPath: p.chooserPath, graphName: p.graphName, contextSource: p.contextSource })),
    // #713 — distance-matching graph authoring
    add_sequence_evaluator:   bp("Add a Sequence Evaluator node (explicit-time player) to an AnimBP graph - the node distance matching drives by setting its ExplicitTime each frame. graphName can be the top-level AnimGraph or a state's inner graph (pass the state name). Defaults bTeleportToExplicitTime=false so time advances and root motion extracts. Connects to the Output Pose by default. Returns nodeGuid for bind_anim_node_function. Params: assetPath (AnimBP), sequencePath? (AnimSequence to evaluate), graphName? (default AnimGraph), explicitTime?, shouldLoop?, teleportToExplicitTime? (default false), connectToOutput? (default true) (#713)", "add_sequence_evaluator", (p) => ({ assetPath: p.assetPath, sequencePath: p.sequencePath, graphName: p.graphName, explicitTime: p.explicitTime, shouldLoop: p.shouldLoop, teleportToExplicitTime: p.teleportToExplicitTime, connectToOutput: p.connectToOutput })),
    bind_anim_node_function:  bp("Bind a thread-safe anim-node function to an anim graph node's update slot - the mechanism distance matching uses to advance a Sequence Evaluator's explicit time each frame (function calls AnimDistanceMatchingLibrary::DistanceMatchToTarget / AdvanceTimeByDistanceMatching). The function must already exist on the AnimBP (create it as a BlueprintThreadSafe function first). Identify the node by nodeGuid (from add_sequence_evaluator / add_*_node). Params: assetPath (AnimBP), nodeGuid, functionName, graphName? (default AnimGraph), binding? ('update' (default)|'becomeRelevant'|'initialUpdate') (#713)", "bind_anim_node_function", (p) => ({ assetPath: p.assetPath, nodeGuid: p.nodeGuid, functionName: p.functionName, graphName: p.graphName, binding: p.binding })),
    // v1.0.0-rc.2 — #153, #154 (animation authoring gaps)
    set_sequence_properties: bp("Batch-set properties on AnimSequence assets. If a path is a Montage and resolveFromMontages is true (default), resolves to its first AnimSequence. Params: assetPaths[], properties{enableRootMotion?, forceRootLock?, useNormalizedRootMotionScale?, rootMotionRootLock?}, resolveFromMontages?", "set_sequence_properties"),
    bake_root_motion_from_bone: bp("Bake delta translation from a source bone (e.g. pelvis) onto the root bone across the whole sequence; compensates the source bone so world-space position is unchanged. Params: assetPath, sourceBone, rootBone? (default 'root'), axes? (default ['x','y']), interpolation? ('linear'|'per_frame', default 'linear')", "bake_root_motion_from_bone"),
    // #419/#420 — live-actor skeletal operations (moved from level for proper domain alignment)
    get_bone_transform: bp("Read a bone or socket transform on a live actor's SkeletalMeshComponent. Wraps GetBoneTransform / GetSocketTransform. Params: actorLabel, boneName (or socket name), componentName? (default: CharacterMesh0 / Mesh / first SK component), world? (auto|pie|game|editor, default auto), space? (world|component|local, default world). Returns location, rotation, scale (#420)", "get_bone_transform", (p) => ({ actorLabel: p.actorLabel, boneName: p.boneName, componentName: p.componentName, world: p.world, space: p.space })),
    list_bones: bp("List bones in a live actor's SkeletalMeshComponent ref skeleton (name, index, parent). Params: actorLabel, componentName?, world? (auto|pie|game|editor, default auto) (#420)", "list_bones", (p) => ({ actorLabel: p.actorLabel, componentName: p.componentName, world: p.world })),
    rebind_leader_pose: bp("Re-bind every secondary SkeletalMeshComponent on an actor to a body component (default CharacterMesh0 / Mesh). One-call fix for the 'character explodes after rotating the actor' failure mode. Params: actorLabel, bodyComponent? (#419)", "rebind_leader_pose", (p) => ({ actorLabel: p.actorLabel, bodyComponent: p.bodyComponent })),
    preview_animation: bp("Toggle bUpdateAnimationInEditor + VisibilityBasedAnimTickOption=AlwaysTickPoseAndRefreshBones on every SkeletalMeshComponent of an actor. Bypasses the 'cannot be edited on templates' guard for level instances. Params: actorLabel, enabled (#419/#420)", "preview_animation", (p) => ({ actorLabel: p.actorLabel, enabled: p.enabled })),
  },
  undefined,
  {
    assetPath: z.string().optional(),
    directory: z.string().optional(),
    recursive: z.boolean().optional(),
    targetTrackCount: z.number().optional().describe("Flag sequences with more than this many bone tracks"),
    includeTrackNames: z.boolean().optional().describe("Include full bone track name arrays in scan_animation_tracks results"),
    animSequencePath: z.string().optional(),
    skeletonPath: z.string().optional(),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    axisHorizontal: z.string().optional(),
    axisVertical: z.string().optional(),
    horizontalMin: z.number().optional(),
    horizontalMax: z.number().optional(),
    verticalMin: z.number().optional(),
    verticalMax: z.number().optional(),
    gridNumHorizontal: z.number().optional(),
    gridNumVertical: z.number().optional(),
    axis: z.record(z.unknown()).optional().describe("populate_blendspace: axis params for axis 0 (#459)"),
    blendspaceAxes: z.array(z.record(z.unknown())).optional().describe("populate_blendspace: per-axis params array (alias for backwards-compat) (#459)"),
    axisIndex: z.number().optional().describe("populate_blendspace: axis index when using 'axis' on a 2D blendspace (#459)"),
    axisName: z.string().optional().describe("create_blendspace_1d axis display name (#459)"),
    axisMin: z.number().optional(),
    axisMax: z.number().optional(),
    gridNum: z.number().optional(),
    samples: z.array(z.record(z.unknown())).optional().describe("populate_blendspace: [{animationPath, x, y?}] (#459)"),
    clearExisting: z.boolean().optional().describe("populate_blendspace: clear existing samples before adding new ones (default true) (#459)"),
    notifyName: z.string().optional(),
    triggerTime: z.number().optional(),
    notifyClass: z.string().optional(),
    slotIndex: z.number().optional(),
    segmentIndex: z.number().optional().describe("set_montage_sequence: replace only this segment index within the slot (#626)"),
    sequenceLength: z.number().optional(),
    rateScale: z.number().optional(),
    blendIn: z.number().optional(),
    blendOut: z.number().optional(),
    numFrames: z.number().optional(),
    frameRate: z.number().optional(),
    boneName: z.string().optional(),
    boneNames: z.array(z.string()).optional(),
    parentClass: z.string().optional().describe("Parent AnimInstance class name for create_anim_blueprint"),
    // State machine params
    stateMachineName: z.string().optional(),
    stateName: z.string().optional(),
    fromState: z.string().optional(),
    toState: z.string().optional(),
    animAssetPath: z.string().optional().describe("Path to animation sequence or blendspace"),
    blendDuration: z.number().optional(),
    blendLogic: z.string().optional().describe("Standard or Inertialization"),
    variableName: z.string().optional().describe("Bool variable name for set_transition_condition (#707)"),
    transitionGuid: z.string().optional().describe("Transition GUID selector for set_transition_condition (#707)"),
    negate: z.boolean().optional().describe("Negate the bool condition in set_transition_condition (#707)"),
    graphName: z.string().optional().describe("Target graph name (default: AnimGraph)"),
    // Curve params (#79 / #24)
    curveName: z.string().optional().describe("Curve name for add_curve"),
    curveType: z.string().optional().describe("Curve type (default: float)"),
    // #712 — direct float-curve values + animation modifiers
    keys: z.array(z.object({ time: z.number(), value: z.number(), interp: z.string().optional() })).optional().describe("set_anim_curve_keys: [{time, value, interp?}] keyframes"),
    modifierClass: z.string().optional().describe("apply_animation_modifier: UAnimationModifier subclass (short name e.g. 'DistanceCurveModifier' or /Script path)"),
    props: z.record(z.any()).optional().describe("apply_animation_modifier: modifier EditAnywhere property values"),
    // #713 — distance-matching graph authoring
    nodeGuid: z.string().optional().describe("bind_anim_node_function: target anim graph node GUID (from add_sequence_evaluator / add_*_node)"),
    functionName: z.string().optional().describe("bind_anim_node_function: thread-safe anim-node function name to bind"),
    binding: z.string().optional().describe("bind_anim_node_function: 'update' (default), 'becomeRelevant', or 'initialUpdate'"),
    explicitTime: z.number().optional().describe("add_sequence_evaluator: initial ExplicitTime"),
    shouldLoop: z.boolean().optional().describe("add_sequence_evaluator: bShouldLoop"),
    teleportToExplicitTime: z.boolean().optional().describe("add_sequence_evaluator: bTeleportToExplicitTime (default false so time advances / root motion extracts)"),
    // Montage slot & section params (#78, #27)
    slotName: z.string().optional().describe("Slot name for set_montage_slot"),
    trackIndex: z.number().optional().describe("Slot track index (default: 0)"),
    sectionName: z.string().optional().describe("Section name for add_montage_section"),
    startTime: z.number().optional().describe("Start time for montage section"),
    linkedSection: z.string().optional().describe("Next section name to link to"),
    // IK Rig params (#93)
    skeletalMeshPath: z.string().optional().describe("Path to skeletal mesh for create_ik_rig / compare_curves_to_morph_targets (#656)"),
    animPath: z.string().optional().describe("compare_curves_to_morph_targets: AnimSequence or PoseAsset path (#656)"),
    nodeClass: z.string().optional().describe("inspect_anim_nodes: node class substring filter, e.g. PoseDriver (#657)"),
    enableRootMotion: z.boolean().optional(),
    forceRootLock: z.boolean().optional(),
    useNormalizedRootMotionScale: z.boolean().optional(),
    rootMotionRootLock: z.string().optional().describe("RefPose|AnimFirstFrame|Zero"),
    sourceBone: z.string().optional(),
    targetBone: z.string().optional(),
    virtualBoneName: z.string().optional(),
    retargetRoot: z.string().optional().describe("Retarget root bone name for IK Rig"),
    sourceRig: z.string().optional().describe("Source IKRig path for create_ik_retargeter"),
    targetRig: z.string().optional().describe("Target IKRig path for create_ik_retargeter"),
    rigPath: z.string().optional().describe("IK Rig path for set_ik_rig_mesh / set_ik_retargeter_rig (#701/#703)"),
    meshPath: z.string().optional().describe("Skeletal mesh path for set_ik_rig_mesh (#701)"),
    retargeterPath: z.string().optional().describe("IK Retargeter path (#701/#703)"),
    side: z.string().optional().describe("source|target for retargeter rig/pose actions (#701/#703)"),
    sourceMesh: z.string().optional().describe("batch_retarget_animations: source skeletal mesh (#701)"),
    targetMesh: z.string().optional().describe("batch_retarget_animations: target skeletal mesh (#701)"),
    animPaths: z.array(z.string()).optional().describe("batch_retarget_animations: AnimSequence paths to bake (#701)"),
    prefix: z.string().optional().describe("batch_retarget_animations: output name prefix (#701)"),
    suffix: z.string().optional().describe("batch_retarget_animations: output name suffix (#701)"),
    overwrite: z.boolean().optional().describe("batch_retarget_animations: overwrite existing outputs (#701)"),
    outputPath: z.string().optional().describe("batch_retarget_animations: destination folder for baked assets (#701)"),
    autoMapChains: z.boolean().optional().describe("create_ik_retargeter: assign rigs to ops + AutoMapChains after creation (default true)"),
    onConflict: z.string().optional().describe("Asset-creation conflict policy: skip (default) | error | overwrite"),
    frames: z.array(z.number()).optional().describe("Specific frames to sample for read_bone_track"),
    chains: z.array(z.object({
      name: z.string(),
      startBone: z.string(),
      endBone: z.string(),
      goal: z.string().optional(),
    })).optional().describe("IK retarget chains for create_ik_rig"),
    keyframes: z.array(z.object({
      frame: z.number(),
      location: Vec3.optional(),
      rotation: Quat.optional(),
      scale: Vec3.optional(),
    })).optional(),
    tracks: z.array(z.object({
      bone: z.string(),
      keyframes: z.array(z.object({
        frame: z.number().optional(),
        location: Vec3.optional(),
        rotation: Quat.optional(),
        scale: Vec3.optional(),
      })),
    })).optional().describe("Per-bone keyframe arrays for bake_keyframes_batch (#540)"),
    save: z.boolean().optional().describe("bake_keyframes_batch: save the asset after baking (default true)"),
    // PoseSearch (v0.7.15)
    schemaPath: z.string().optional().describe("Path to a UPoseSearchSchema asset"),
    sequencePath: z.string().optional().describe("Animation asset path to add to a PoseSearchDatabase"),
    wait: z.boolean().optional().describe("build_pose_search_index: block until the async build resolves (default true)"),
    // #684 per-clip flags + bulk clip authoring
    mirror: z.string().optional().describe("PoseSearch clip mirror option: 'original' | 'mirrored' | 'both'"),
    disableReselection: z.boolean().optional().describe("PoseSearch clip: disallow reselecting poses from the same asset"),
    sampleStart: z.number().optional().describe("PoseSearch clip sampling range start (seconds); [0,0] = whole clip"),
    sampleEnd: z.number().optional().describe("PoseSearch clip sampling range end (seconds); [0,0] = whole clip"),
    clips: z.array(z.any()).optional().describe("set_pose_search_clips: array of clip entries ({sequencePath, mirror?, disableReselection?, sampleStart?, sampleEnd?, enabled?}) or bare path strings"),
    // Motion Matching content pipeline (schema / mirror / normalization / tuning)
    sampleRate: z.number().optional().describe("create_pose_search_schema: schema sample rate (default 30)"),
    addDefaultChannels: z.boolean().optional().describe("create_pose_search_schema: add Trajectory+Pose default channels (default true)"),
    mirrorDataTablePath: z.string().optional().describe("create_pose_search_schema: optional MirrorDataTable to bind"),
    bones: z.array(z.any()).optional().describe("add_pose_search_schema_pose_channel: [{bone, flags?, weight?}] or bone-name strings; also add_pose_search_schema_trajectory_channel reuses 'samples'"),
    weight: z.number().optional().describe("Channel weight for pose/trajectory channels"),
    expressions: z.array(z.any()).optional().describe("create_mirror_data_table: [{find, replace, method?}] find/replace bone-name rules"),
    mirrorAxis: z.string().optional().describe("create_mirror_data_table: mirror axis (default X)"),
    databases: z.array(z.string()).optional().describe("create_pose_search_normalization_set: PoseSearchDatabase paths to normalize together"),
    continuingPoseCostBias: z.number().optional().describe("set_pose_search_database_settings: bias to keep playing the current clip"),
    baseCostBias: z.number().optional().describe("set_pose_search_database_settings: flat cost added to every pose"),
    loopingCostBias: z.number().optional().describe("set_pose_search_database_settings: bias for looping clips"),
    kdTreeQueryNumNeighbors: z.number().optional().describe("set_pose_search_database_settings: KD-tree neighbours to consider"),
    numberOfPrincipalComponents: z.number().optional().describe("set_pose_search_database_settings: PCA components for PCAKDTree mode"),
    poseSearchMode: z.string().optional().describe("set_pose_search_database_settings: bruteforce | pcakdtree | vptree | eventonly"),
    normalizationSetPath: z.string().optional().describe("set_pose_search_database_settings: PoseSearchNormalizationSet to assign"),
    databasePath: z.string().optional().describe("add_motion_matching_node: PoseSearchDatabase the node searches"),
    connectToOutput: z.boolean().optional().describe("add_motion_matching_node: wire the node to the Output Pose (default true)"),
    blendTime: z.number().optional().describe("add_motion_matching_node: inertial blend time"),
    poseCount: z.number().optional().describe("add_pose_history_node: number of history poses to retain"),
    samplingInterval: z.number().optional().describe("add_pose_history_node: seconds between history samples"),
    generateTrajectory: z.boolean().optional().describe("add_pose_history_node: self-generate trajectory (default true)"),
    trajectoryHistoryCount: z.number().optional().describe("add_pose_history_node: generated trajectory history samples"),
    trajectoryPredictionCount: z.number().optional().describe("add_pose_history_node: generated trajectory prediction samples"),
    insertBeforeOutput: z.boolean().optional().describe("add_pose_history_node: splice into the pose chain feeding Output Pose (default true)"),
    chooserPath: z.string().optional().describe("set_motion_matching_chooser: ChooserTable that selects the database"),
    contextSource: z.string().optional().describe("set_motion_matching_chooser: chooser context object - 'self' (anim instance, default) or 'pawn' (owning pawn)"),
    // #153 / #154
    assetPaths: z.array(z.string()).optional().describe("Asset paths (batch) for set_sequence_properties"),
    properties: z.record(z.any()).optional().describe("Property dict for set_sequence_properties"),
    resolveFromMontages: z.boolean().optional().describe("Resolve AnimMontage inputs to first anim reference (default true)"),
    rootBone: z.string().optional().describe("Root bone name for bake_root_motion_from_bone (default 'root')"),
    axes: z.array(z.string()).optional().describe("Axes to bake ('x','y','z') for bake_root_motion_from_bone"),
    interpolation: z.string().optional().describe("bake_root_motion_from_bone: 'linear' (default) or 'per_frame'"),
    space: z.string().optional().describe("Bone-space frame. get_bone_transforms (ref skeleton): 'local' (default) | 'component'. get_bone_transform (live actor): 'world' (default) | 'component' | 'local'"),
    world: z.string().optional().describe("World scope for live actor skeletal queries: auto (default, prefer PIE), pie/game, or editor"),
    animation: z.string().optional().describe("AnimSequence path for add_blend_sample / set_blend_sample"),
    sampleIndex: z.number().optional().describe("BlendSpace sample index for set_blend_sample"),
    position: z.object({ x: z.number().optional(), y: z.number().optional() }).optional().describe("BlendSpace sample position {x,y}"),
    x: z.number().optional(),
    y: z.number().optional(),
    // Live-actor skeletal operations (moved from level)
    actorLabel: z.string().optional().describe("Actor label for live skeletal queries"),
    componentName: z.string().optional().describe("SkeletalMeshComponent name (default: CharacterMesh0 / Mesh)"),
    bodyComponent: z.string().optional().describe("rebind_leader_pose: explicit body component name"),
    enabled: z.boolean().optional().describe("preview_animation: toggle on/off"),
  },
);
