import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Vec3, Rotator } from "../schemas.js";

export const gameplayTool: ToolDef = categoryTool(
  "gameplay",
  "Gameplay systems: physics, collision, navigation, input, behavior trees, AI (EQS, perception, State Trees, Smart Objects), game framework.",
  {
    set_collision_profile:  bp("Set collision preset. Params: actorLabel, profileName", "set_collision_profile"),
    set_simulate_physics:   bp("Toggle physics. Params: actorLabel, simulate", "set_simulate_physics"),
    set_collision_enabled:  bp("Set collision mode. Params: actorLabel, collisionEnabled", "set_collision_enabled"),
    set_physics_properties: bp("Set mass/damping/gravity. Params: actorLabel, mass?, linearDamping?, angularDamping?, enableGravity?", "set_physics_properties"),
    rebuild_navigation:     bp("Rebuild navmesh", "rebuild_navigation"),
    find_nav_path:          bp("Synchronous nav-path query between two world points. Returns valid/partial/length plus the polyline. The standard 'why doesn't my AI move?' diagnostic. Params: start (Vec3), end (Vec3), pathfindingContext? (actorLabel - uses its agent + filter) (#424)", "find_nav_path", (p) => ({ start: p.start, end: p.end, pathfindingContext: p.pathfindingContext })),
    list_nav_invokers:      bp("Enumerate actors carrying a NavigationInvokerComponent + their tile generation/removal radii. Diagnoses 'no navmesh in this region' caused by missing or mis-sized invokers (#424)", "list_nav_invokers"),
    get_navmesh_info:       bp("Query nav system", "get_navmesh_info"),
    project_to_nav:         bp("Project point to navmesh. Params: location, extent?", "project_point_to_navigation"),
    spawn_nav_modifier:     bp("Place nav modifier. Params: location, extent?, areaClass?", "spawn_nav_modifier_volume"),
    create_input_action:    bp("Create InputAction. Params: name, packagePath?, valueType?", "create_input_action"),
    create_input_mapping:   bp("Create InputMappingContext. Params: name, packagePath?", "create_input_mapping_context"),
    list_input_assets:      bp("List input assets. Params: directory?, recursive?", "list_input_assets"),
    read_imc:               bp("Read InputMappingContext mappings. Params: imcPath. Returns {key, inputAction, triggers[], modifiers[]}.", "read_imc"),
    list_input_mappings:    bp("Alias for read_imc. List key→action bindings with triggers/modifiers. Params: imcPath", "list_imc_mappings"),
    add_imc_mapping:        bp("Add key mapping to IMC. Params: imcPath, inputActionPath, key", "add_imc_mapping"),
    set_mapping_modifiers:  bp("Set modifiers/triggers on an IMC mapping. Params: imcPath, mappingIndex?, modifiers?, triggers?", "set_mapping_modifiers"),
    remove_imc_mapping:     bp("(#158) Remove an IMC mapping. Params: imcPath, mappingIndex? | (inputActionPath? + key?)", "remove_imc_mapping"),
    set_imc_mapping_key:    bp("(#158) Rebind an IMC mapping to a new key. Params: imcPath, newKey, mappingIndex? | key? | inputActionPath?", "set_imc_mapping_key"),
    set_imc_mapping_action: bp("(#158) Retarget an IMC mapping to a different InputAction. Params: imcPath, newInputActionPath, mappingIndex? | key? | inputActionPath?", "set_imc_mapping_action"),
    list_behavior_trees:    bp("List behavior trees. Params: directory?, recursive?", "list_behavior_trees"),
    get_behavior_tree_info: bp("Inspect behavior tree (top-level + blackboard). Params: assetPath", "get_behavior_tree_info"),
    read_behavior_tree_graph: bp("Walk BT tree: composites, tasks, decorators, services with blackboard keys. Params: assetPath", "read_behavior_tree_graph"),
    create_blackboard:      bp("Create Blackboard. Params: name, packagePath?", "create_blackboard"),
    add_blackboard_key:     bp("Add a typed key to a Blackboard asset. Params: blackboardPath, keyName, keyType (Bool|Int|Float|String|Name|Vector|Rotator|Object|Class|Enum), baseClass? (for Object/Class types; e.g. /Script/Engine.Actor) (#250)", "add_blackboard_key", (p) => ({ blackboardPath: p.blackboardPath, keyName: p.keyName, keyType: p.keyType, baseClass: p.baseClass })),
    set_behavior_tree_blackboard: bp("Rebind a BehaviorTree asset's BlackboardAsset reference. Params: behaviorTreePath, blackboardPath. The C++ field is protected so reflection is the only writable path (#250)", "set_behavior_tree_blackboard", (p) => ({ behaviorTreePath: p.behaviorTreePath, blackboardPath: p.blackboardPath })),
    create_behavior_tree:   bp("Create behavior tree. Params: name, packagePath?, blackboardPath?", "create_behavior_tree"),
    create_eqs_query:       bp("Create EQS query. Params: name, packagePath?", "create_eqs_query"),
    list_eqs_queries:       bp("List EQS queries. Params: directory?", "list_eqs_queries"),
    add_perception:         bp("Add AIPerceptionComponent. Params: blueprintPath, senses?", "add_perception_component"),
    configure_sense:        bp("Configure perception sense. Params: blueprintPath, senseType, settings?", "configure_ai_perception_sense"),
    create_state_tree:      bp("Create StateTree. Params: name, packagePath?", "create_state_tree"),
    list_state_trees:       bp("List StateTrees. Params: directory?", "list_state_trees"),
    add_state_tree_component: bp("Add StateTreeComponent. Params: blueprintPath", "add_state_tree_component"),
    create_smart_object_def: bp("Create SmartObjectDefinition. Params: name, packagePath?", "create_smart_object_definition"),
    add_smart_object_component: bp("Add SmartObjectComponent. Params: blueprintPath", "add_smart_object_component"),
    add_smart_object_slot: bp("Append a FSmartObjectSlotDefinition to a SmartObjectDefinition's Slots array. Params: assetPath, name?, offset? ({x,y,z}), rotation? ({pitch,yaw,roll}), tags? (array). Returns the new slotIndex. Rollback removes the slot (#416)", "add_smart_object_slot", (p) => ({ assetPath: p.assetPath, name: p.name, offset: p.offset, rotation: p.rotation, tags: p.tags })),
    set_smart_object_slot: bp("Mutate an existing slot's offset/rotation/tags. Params: assetPath, slotIndex, offset? ({x,y,z}), rotation? ({pitch,yaw,roll}), tags? (array). Omitted fields keep their current values (#416)", "set_smart_object_slot", (p) => ({ assetPath: p.assetPath, slotIndex: p.slotIndex, name: p.name, offset: p.offset, rotation: p.rotation, tags: p.tags })),
    remove_smart_object_slot: bp("Remove a slot by index. Idempotent: out-of-range returns alreadyDeleted=true. Params: assetPath, slotIndex (#416)", "remove_smart_object_slot", (p) => ({ assetPath: p.assetPath, slotIndex: p.slotIndex })),
    list_smart_object_slots: bp("List slots on a SmartObjectDefinition with index, offset, rotation, and raw text. Params: assetPath (#416)", "list_smart_object_slots", (p) => ({ assetPath: p.assetPath })),
    add_smart_object_slot_behavior: bp("Attach a behavior definition (UBehaviorDefinition asset or class) to a slot's BehaviorDefinitions array. Pass instanceProperties to seed UPROPERTYs on a freshly-spawned class-instance. Params: assetPath, slotIndex, behaviorClass (asset path or class path), instanceProperties? (#416)", "add_smart_object_slot_behavior", (p) => ({ assetPath: p.assetPath, slotIndex: p.slotIndex, behaviorClass: p.behaviorClass, instanceProperties: p.instanceProperties })),
    inspect_pie:            bp("Inspect PIE runtime. Params: actorLabel?", "inspect_pie"),
    get_pie_anim_state:     bp("Get PIE anim instance state. Params: actorLabel", "get_pie_anim_state"),
    get_pie_anim_properties: bp("Read arbitrary UPROPERTY values on a PIE actor's AnimInstance (#139). Params: actorLabel, propertyNames? (omit = dump all)", "get_pie_anim_properties", (p) => ({ actorLabel: p.actorLabel, propertyNames: p.propertyNames })),
    get_pie_subsystem_state: bp("Read UPROPERTY values on a running subsystem in PIE (#139). Params: subsystemClass, scope? (game|world|engine|localplayer), propertyNames?", "get_pie_subsystem_state", (p) => ({ subsystemClass: p.subsystemClass, scope: p.scope, propertyNames: p.propertyNames })),
    create_game_mode:       bp("Create GameMode BP. Params: name, packagePath?, parentClass?, defaults?", "create_game_mode"),
    create_game_state:      bp("Create GameState BP. Params: name, packagePath?, parentClass?", "create_game_state"),
    create_player_controller: bp("Create PlayerController BP. Params: name, packagePath?, parentClass?", "create_player_controller"),
    create_player_state:    bp("Create PlayerState BP. Params: name, packagePath?", "create_player_state"),
    create_hud:             bp("Create HUD BP. Params: name, packagePath?", "create_hud"),
    set_world_game_mode:    bp("Set level GameMode override. Params: gameModePath", "set_world_game_mode"),
    get_framework_info:     bp("Get level framework classes", "get_game_framework_info"),
    get_navmesh_details:    bp("Read RecastNavMesh generation params (cellSize, agentHeight, maxStepHeight, etc.) (#163)", "get_navmesh_details"),
    apply_damage_in_pie:    bp("Apply damage to PIE actor. Params: actorLabel, baseDamage?, damageTypeClass? (#186)", "apply_damage_in_pie"),
  },
  undefined,
  {
    actorLabel: z.string().optional(),
    profileName: z.string().optional(),
    simulate: z.boolean().optional(),
    collisionEnabled: z.string().optional(),
    mass: z.number().optional(),
    linearDamping: z.number().optional(),
    angularDamping: z.number().optional(),
    enableGravity: z.boolean().optional(),
    location: Vec3.optional(),
    extent: Vec3.optional(),
    start: Vec3.optional().describe("find_nav_path: query start"),
    end: Vec3.optional().describe("find_nav_path: query end"),
    pathfindingContext: z.string().optional().describe("find_nav_path: actor label whose agent/filter the query uses"),
    areaClass: z.string().optional(),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    valueType: z.string().optional(),
    directory: z.string().optional(),
    recursive: z.boolean().optional(),
    assetPath: z.string().optional(),
    blackboardPath: z.string().optional(),
    behaviorTreePath: z.string().optional().describe("BehaviorTree asset path for set_behavior_tree_blackboard"),
    keyName: z.string().optional().describe("Blackboard key name for add_blackboard_key"),
    keyType: z.string().optional().describe("Blackboard key type: Bool, Int, Float, String, Name, Vector, Rotator, Object, Class, Enum"),
    baseClass: z.string().optional().describe("Base class path for Object/Class blackboard keys (e.g. /Script/Engine.Actor)"),
    blueprintPath: z.string().optional(),
    slotIndex: z.number().optional().describe("SmartObject slot index"),
    offset: Vec3.optional().describe("SmartObject slot offset"),
    rotation: Rotator.optional().describe("SmartObject slot rotation"),
    tags: z.array(z.unknown()).optional().describe("SmartObject slot tags (gameplay tag strings or struct shapes)"),
    behaviorClass: z.string().optional().describe("SmartObject behavior class or asset path for add_smart_object_slot_behavior"),
    instanceProperties: z.record(z.unknown()).optional().describe("Property writes to apply to a freshly-spawned behavior instance"),
    senses: z.array(z.string()).optional(),
    senseType: z.string().optional(),
    settings: z.record(z.unknown()).optional(),
    parentClass: z.string().optional(),
    defaults: z.record(z.string()).optional(),
    gameModePath: z.string().optional(),
    imcPath: z.string().optional(),
    inputActionPath: z.string().optional(),
    key: z.string().optional(),
    newKey: z.string().optional().describe("New FKey name for set_imc_mapping_key"),
    newInputActionPath: z.string().optional().describe("New InputAction path for set_imc_mapping_action"),
    mappingIndex: z.number().optional().describe("Index of mapping in IMC (default 0)"),
    modifiers: z.array(z.record(z.unknown())).optional().describe("Array of modifier objects: {type, ...props}"),
    triggers: z.array(z.record(z.unknown())).optional().describe("Array of trigger objects: {type, ...props}"),
    propertyNames: z.array(z.string()).optional().describe("Property names to read for get_pie_anim_properties/get_pie_subsystem_state"),
    subsystemClass: z.string().optional().describe("Subsystem class path or short name for get_pie_subsystem_state"),
    scope: z.enum(["game", "world", "engine", "localplayer"]).optional().describe("Subsystem scope for get_pie_subsystem_state (default: game)"),
    baseDamage: z.number().optional().describe("Damage amount for apply_damage_in_pie (default 10)"),
    damageTypeClass: z.string().optional().describe("Damage type class for apply_damage_in_pie"),
  },
);
