import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { actions as epicActions, schema as epicSchema } from "./epic/gas.generated.js";

export const gasTool: ToolDef = categoryTool(
  "gas",
  "Gameplay Ability System: abilities, effects, attribute sets, cues.",
  {
    add_asc:             bp("mutate", "Add AbilitySystemComponent. Params: blueprintPath, componentName?", "add_ability_system_component"),
    create_attribute_set: bp("mutate", "Create AttributeSet BP. Params: name, packagePath?", "create_attribute_set"),
    add_attribute:       bp("mutate", "Add attribute to set. Params: attributeSetPath, attributeName, defaultValue?", "add_attribute"),
    create_ability:      bp("mutate", "Create GameplayAbility BP. Params: name, packagePath?, parentClass?", "create_gameplay_ability"),
    set_ability_tags:    bp("mutate", "Set tags on ability. Each container passed is written whole, so the inverse is this same call carrying the tags that were in it; containers you do not pass are left alone and are not in the record. unchanged=true means the tags a written container ended up holding are the same set it already held, compared both ways, not merely that the caller passed nothing. Params: abilityPath, ability_tags?, cancel_abilities_with_tag?, block_abilities_with_tag?, activation_required_tags?, activation_blocked_tags?", "set_ability_tags"),
    create_effect:       bp("mutate", "Create GameplayEffect BP. Params: name, packagePath?, durationPolicy?", "create_gameplay_effect"),
    set_effect_modifier: bp("mutate", "Add or update a modifier on a GameplayEffect, matched on attribute + operation. Overwriting an existing static magnitude rolls back to the value it held, qualified as SetName.Attribute so the inverse cannot land on another set's same-named attribute, and marked lossy because it comes back as a plain ScalableFloat constant. A magnitude that CHANGES WITH EFFECT LEVEL gets no record: it is probed at levels 1, 2 and 10, and one that moves is curve-table-backed, so writing a single constant would destroy the binding. APPENDING a new modifier has no inverse either, because no action removes a modifier from an effect; the response says rollbackPossible=false rather than offering a magnitude of zero as an undo. Params: effectPath, attribute, operation?, magnitude?", "set_effect_modifier"),
    create_cue:          bp("mutate", "Create GameplayCue. Params: name, packagePath?, cueType?", "create_gameplay_cue"),
    get_info:            bp("read", "Inspect GAS setup. Params: blueprintPath", "get_gas_info"),
    set_asc_defaults:    bp("mutate", "Wire an AttributeSet onto a Blueprint's ASC component (DefaultStartingData) so attributes exist at runtime. Idempotent: a set already wired reports existed. No inverse - nothing removes an entry from DefaultStartingData, and removing the whole component would undo more than this did, so the response says rollbackPossible=false. Params: blueprintPath, attributeSet (content path or class name), componentName?, initDataTable? (starting values). Run add_ability_system_component first.", "set_asc_defaults"),
    apply_effect:        bp("mutate", "Apply a GameplayEffect to a live actor's ASC (agnostic stat/damage stimulus - uses the game's own effect). A duration or infinite effect comes back with an effectHandle and rolls back through gas(remove_effect) on that handle. When the effect STACKS - its StackingType is not None and one of its class was already on the ASC - no new active effect is created, the existing handle comes back with a higher stackCount, and the record removes exactly one stack so the stacks that predate the call survive (reported as stackedOntoExisting, marked lossy because the duration refresh does not come back). an instant effect executes into the attribute base values, leaves no handle, and says so through rollbackPossible=false. An effect the ASC refuses reports unchanged=true rather than a bare success. Params: actorLabel OR actorPath, effectClass (content path or class name), level?, setByCaller? ({tag-or-name: magnitude}), world? (auto|pie|editor, default auto)", "apply_effect"),
    remove_effect:       bp("mutate", "Take an active GameplayEffect back off a live actor's ASC - the inverse of apply_effect. Address it by effectHandle (what apply_effect returned, and the only way to remove exactly the effect one call added) or by effectClass, which removes every active effect of that class on the actor. Idempotent: a handle whose effect has already expired reports alreadyRemoved=true rather than failing, so a replayed rollback is safe. Removing exactly one effect rolls back to apply_effect at the level it held, marked lossy because duration, stack count and SetByCaller magnitudes do not survive removal. Instant effects have no handle and cannot be removed - their modifiers are already in the attribute base. Params: actorLabel OR actorPath, effectHandle? OR effectClass?, stacksToRemove? (default -1, the whole effect), world?", "remove_effect", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, effectHandle: p.effectHandle, effectClass: p.effectClass ?? p.effectPath, stacksToRemove: p.stacksToRemove, world: p.world })),
    set_attribute:       bp("mutate", "Set a gameplay attribute's base value on a live actor's ASC (recalculates CurrentValue through the aggregator). Reports unchanged=true when the base value did not move, including when the set's own clamping refused the write. Rolls back by writing the previous base value through the same path, which restores the current value with it because the modifiers are never touched; the record names the attribute QUALIFIED as SetName.Attribute, because a bare name resolves to whichever attribute set the class iterator reaches first and two sets can both declare Health. Params: actorLabel OR actorPath, attribute (Health | SetName.Health), value, world?", "set_attribute"),
    get_attribute:       bp("read", "Read gameplay attribute base + current values on a live actor's ASC. Omit attribute to list all. Params: actorLabel OR actorPath, attribute?, world?", "get_attribute"),
    init_asc:            bp("mutate", "Initialize a live actor's ASC (InitAbilityActorInfo) and optionally instantiate an AttributeSet so attributes are live - the runtime setup step for testing a bridge-authored GAS actor. Reports unchanged=true when the ASC was already initialized for this actor and every set it needs was already registered. No inverse: nothing returns an ASC to uninitialized, and this is what BeginPlay would have done anyway, so the response says rollbackPossible=false and names any AttributeSet it had to CONSTRUCT. Params: actorLabel OR actorPath, attributeSet? (content path or class name), world?", "init_asc"),
    get_asc_state:       bp("read", "Introspect a live actor's ASC: granted ability specs (class, level, inputID, active, dynamicTags) + owned gameplay tags. Params: actorLabel OR actorPath, world? (auto|pie|editor) (#587)", "get_asc_state", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, world: p.world })),
    // #956: get_attribute / set_attribute above only see attribute sets the ASC
    // has already registered, and an actor spawned into the editor world has
    // none: the DSO scan that registers them runs in InitializeComponent, which
    // a world that has not begun play never reaches. These two name the set,
    // resolve the instance through the ASC (never the actor's own pointer, which
    // is not proof the ASC knows about it), and register the actor's own
    // subobject when the ASC has not.
    get_live_attribute_value: bp("mutate", "Read the live value of one FGameplayAttributeData on the attribute set instance actually REGISTERED on an actor's AbilitySystemComponent - equivalent to ASC->GetSet<T>(), not the actor's own subobject pointer. Works in the editor world, where no set is registered yet, by first registering the actor's own sets the way BeginPlay would (set registerOwnerSets=false for a strict read). Returns currentValue and baseValue off the instance plus the aggregator's view of both, and the instance's object path so you can prove which object was read. Gated as a mutation because registering those sets changes the live world; the response reports unchanged=true when it registered nothing, and rollbackPossible=false either way, since nothing un-registers a set the engine would register again at BeginPlay. Params: actorLabel (label or internal name) OR actorPath, attributeSet (content path or class name), attribute (property name, or Set.Property), registerOwnerSets?, world? (#956)", "get_live_attribute_value", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, attributeSet: p.attributeSet, attribute: p.attribute, registerOwnerSets: p.registerOwnerSets, world: p.world })),
    set_live_attribute_value: bp("mutate", "Write the live value of one FGameplayAttributeData on the REGISTERED attribute set instance on an actor's AbilitySystemComponent. valueType=\"current\" (default) writes the attribute data in place, which is what staging a mid-combat state needs; valueType=\"base\" writes through the ASC so the aggregator recomputes the current value, which is what a durable change needs. The set's PreAttributeChange may clamp, so the result reports what was actually stored alongside the previous values and the instance's object path. Reports unchanged=true when neither the value moved nor a set was registered, reading the stored value back because PreAttributeChange can clamp a write to what was already there. The inverse writes the overwritten value back through the same valueType, and is marked lossy when the call also had to register the actor's own attribute sets to reach the value, since that registration stays. Params: actorLabel (label or internal name) OR actorPath, attributeSet, attribute, value, valueType?, registerOwnerSets?, world? (#956)", "set_live_attribute_value", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, attributeSet: p.attributeSet, attribute: p.attribute, value: p.value, valueType: p.valueType, registerOwnerSets: p.registerOwnerSets, world: p.world })),
    grant_ability:       bp("mutate", "Grant a GameplayAbility to a live actor's ASC, which is what makes an authored ability activatable at all - an ability the ASC has never been given does nothing and logs nothing worth reading. Idempotent: granting a class that is already granted returns the existing spec with existed=true rather than a second handle for what the caller thinks of as one ability. Refused on a non-authoritative ASC, because GiveAbility only runs on the authority and would otherwise look like it worked. Returns the spec (handle, level, inputID, active) and a rollback that revokes it. Params: actorLabel OR actorPath, abilityClass (Blueprint path, generated class path, or native class name), level? (default 1), inputId? (default -1), world? (auto|pie|editor)", "grant_ability", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, abilityClass: p.abilityClass, level: p.level, inputId: p.inputId, world: p.world, pieInstance: p.pieInstance })),
    revoke_ability:      bp("mutate", "Remove a granted GameplayAbility from a live actor's ASC. Idempotent: revoking one that is not granted reports alreadyRevoked=true rather than failing, so replaying a rollback is safe. Params: actorLabel OR actorPath, abilityClass, world?", "revoke_ability", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, abilityClass: p.abilityClass, world: p.world, pieInstance: p.pieInstance })),
    get_active_effects:  bp("read", "List every GameplayEffect currently active on a live actor's ASC: effect class, stack count, level, total duration, time remaining, whether it is inhibited, the instigator that applied it, and the tags it grants. Plus the ASC's owned tags. Unfiltered on purpose - the caller is diagnosing, and a filter that hid the effect they were looking for would be the whole problem. Params: actorLabel OR actorPath, world? (auto|pie|editor)", "get_active_effects", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, world: p.world, pieInstance: p.pieInstance })),
    trace_ability_activation: bp("unknown", "Answer why an ability will not activate, which GAS otherwise reports only to the log in a form nothing can read back. Checks in order: is it granted at all (the most common cause, and silent), is it already active without bRetriggerInstancedAbility, which tags it was refused over (the engine reports one relevant-tag set rather than separating 'blocked by' from 'missing', so neither does this - compare them against the returned ownedTags), is it on cooldown (with seconds remaining), and is its cost unmet. Returns wouldActivate plus a blockedBy[] naming each reason. Pass activate=true to also call TryActivateAbility and prove it rather than predict it; a refusal with no blocker found means the ability's own CanActivateAbility override refused. Reports unchanged=true on every path where nothing fired. An activation has no inverse - the ability has already committed its cost, applied its cooldown and run its effects - so the response says rollbackPossible=false. Params: actorLabel OR actorPath, abilityClass, activate? (default false), world?", "trace_ability_activation", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, abilityClass: p.abilityClass, activate: p.activate, world: p.world, pieInstance: p.pieInstance })),

    // -- T4 remainder: input binding -----------------------------------
    // FGameplayAbilitySpec lives in a fast-array serialiser on a LIVE
    // AbilitySystemComponent, so there is no asset for asset(set_property) to
    // aim at, and a write that skipped MarkAbilitySpecDirty would not
    // replicate. That is why these three are handlers and not property writes.
    bind_ability_input:  bp("mutate", "Bind a granted ability to an input id, which is how anything other than a direct TryActivateAbility call ever fires it. GAS addresses input by integer: UAbilitySystemComponent::AbilityLocalInputPressed(id) activates every granted spec whose InputID matches, and the Enhanced Input asset side (gameplay(create_input_action) plus gameplay(add_imc_mapping)) is what turns a key into that call in the game's own input component. Idempotent: re-binding the same id reports unchanged=true. Refused on a non-authoritative ASC, because an ability spec is replicated from the authority and a local write would be overwritten while looking like it worked. Reports sharedWith[] when another granted ability already uses that id, since sending the input then activates all of them. The rollback restores the exact previous id, which is not always -1. Params: actorLabel OR actorPath, abilityClass, inputId, world?, pieInstance?", "bind_ability_input", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, abilityClass: p.abilityClass, inputId: p.inputId, world: p.world, pieInstance: p.pieInstance })),
    clear_ability_input: bp("mutate", "Unbind a granted ability from its input id, setting InputID back to -1 so no input event can reach it. Idempotent: an already-unbound ability reports unchanged=true rather than failing, so replaying a rollback is safe. The rollback re-binds the id that was there. Params: actorLabel OR actorPath, abilityClass, world?, pieInstance?", "clear_ability_input", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, abilityClass: p.abilityClass, world: p.world, pieInstance: p.pieInstance })),
    send_ability_input:  bp("mutate", "Deliver an input event to a live ASC, which fires a bound ability the way the game fires it rather than through a direct activation call. inputEvent=pressed|released calls AbilityLocalInputPressed / AbilityLocalInputReleased for an inputId (or for the id abilityClass is bound to); inputEvent=confirm|cancel calls InputConfirm / InputCancel, which reach targeting actors and take no id. Returns the specs that matched the id with their pressed and active state before and after, so the result says what happened rather than what was asked for. An id nothing is bound to is reported as matchedSpecCount 0, not as an error. pressed and released are a genuine inverse pair and roll back to each other; confirm and cancel have no inverse and say so. Params: actorLabel OR actorPath, inputEvent?, inputId?, abilityClass?, world?, pieInstance?", "send_ability_input", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, inputEvent: p.inputEvent, inputId: p.inputId, abilityClass: p.abilityClass, world: p.world, pieInstance: p.pieInstance })),

    // -- T4 remainder: gameplay cues -----------------------------------
    // GameplayCues IS a UPROPERTY array, so a property write could reach it.
    // It would also happily store a tag the tag manager never heard of, a tag
    // outside the GameplayCue root, or a tag no notify answers - three ways to
    // author a cue that silently does nothing. These check all three.
    add_effect_cue:      bp("mutate", "Link a GameplayCue tag to a GameplayEffect, so applying the effect fires the cue. Refuses a tag the tag manager does not know (writing one would store an invalid tag and the cue would never fire; create it first with reflection(create_tag)) and a tag outside the GameplayCue root (the cue system routes nothing else). Reports whether any GameplayCueNotify actually answers the tag, matching a parent tag the way the cue system does, and warns when none does. Idempotent on the tag: re-adding reports existed, changing the level range reports updated. Params: effectPath, cueTag, minLevel?, maxLevel?, magnitudeAttribute?", "add_effect_cue", (p) => ({ effectPath: p.effectPath ?? p.effectClass, cueTag: p.cueTag, minLevel: p.minLevel, maxLevel: p.maxLevel, magnitudeAttribute: p.magnitudeAttribute })),
    remove_effect_cue:   bp("mutate", "Unlink a GameplayCue tag from a GameplayEffect. Accepts a tag that is no longer registered, because cleaning up after a deleted tag is exactly what this has to be able to do. Drops a cue entry left with no tags rather than leaving a blank row. Idempotent: a tag that is not linked reports alreadyRemoved=true. Params: effectPath, cueTag", "remove_effect_cue", (p) => ({ effectPath: p.effectPath ?? p.effectClass, cueTag: p.cueTag })),
    validate_cue_coverage: bp("read", "Audit every GameplayEffect against every GameplayCueNotify in the project and report which cue links fire nothing. Resolves each cue tag the way the cue system does, falling back to a parent tag, so a notify on GameplayCue.Damage counts as covering GameplayCue.Damage.Fire and is reported as a parent match rather than a false positive. Problems it names: a cue tag with no notify on it or any parent, a cue entry with no tag at all, a cue tag outside the GameplayCue root (inert), a notify with no GameplayCueTag (unreachable), and duplicate tags across notifies. Also reports orphan notifies that no effect references, which is usually a rename done on one side only. Reads the asset registry rather than the cue manager index, so a cold index does not read as 'no cues exist'; the manager's own counts come back alongside. Params: directory?, effectPath?, maxEffects?", "validate_cue_coverage", (p) => ({ directory: p.directory, effectPath: p.effectPath ?? p.effectClass, maxEffects: p.maxEffects })),

    // -- T4 remainder: attribute clamping and meta attributes ----------
    audit_attributes:    bp("read", "Report what is provable about an AttributeSet: whether it can clamp at all, which attributes replicate and carry an OnRep, which have a paired Max attribute, and which look like meta attributes. There is deliberately no configure_attribute_clamping counterpart, because UE 5.8 has no data-driven clamp: PreAttributeChange and PreAttributeBaseChange are plain C++ virtuals rather than UFUNCTIONs, so a Blueprint AttributeSet can never clamp and this says so outright instead of pretending to configure one. On a native set, pass probeClamping=true with a live actor to MEASURE an existing clamp by driving PreAttributeChange with extreme values rather than guessing from the class; the probe runs the project's own code so it needs a registered live set, never a class default object. A strict read: unlike get_live_attribute_value it never registers the actor's own sets, so an actor whose ASC has none is told which call registers one. Everything about an attribute set that IS a property stays reachable through asset(set_property) on its Blueprint CDO. Params: attributeSet OR actorLabel OR actorPath, probeClamping?, world?, pieInstance?", "audit_attributes", (p) => ({ attributeSet: p.attributeSet, actorLabel: p.actorLabel, actorPath: p.actorPath, probeClamping: p.probeClamping, world: p.world, pieInstance: p.pieInstance })),

    // -- T5 remainder: snapshot and diff -------------------------------
    capture_gas_state:   bp("mutate", "Capture an actor's whole ability-system state as one snapshot: granted abilities with level, input id, active count and dynamic tags; every active effect with its stack count, level, duration, time remaining, inhibition and instigator; every attribute with BOTH its base and current value; owned gameplay tags with their counts; and the tags currently blocking activation. Stores it under snapshotId (generated when omitted) and also returns it, so a caller that needs it to outlive the editor session keeps the object; the store holds the 64 most recent and is emptied by a restart. Pass compareWith to diff this capture against an earlier snapshot id in the same call, which is the whole capture-act-compare loop in two calls. The diff lives here rather than on compare_gas_states because capturing registers the actor's attribute sets on its ASC where a world has not begun play, so it is gated as the mutation it is. Params: actorLabel OR actorPath, snapshotId?, compareWith?, registerOwnerSets?, world?, pieInstance?", "capture_gas_state", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, snapshotId: p.snapshotId, compareWith: p.compareWith, registerOwnerSets: p.registerOwnerSets, world: p.world, pieInstance: p.pieInstance })),
    compare_gas_states:  bp("read", "Diff two GAS snapshots and name each change rather than handing back two blobs. Every entry in changes[] carries a kind (ability_granted, ability_revoked, ability_level_changed, ability_input_changed, ability_activated, ability_ended, effect_applied, effect_removed, effect_stack_changed, effect_level_changed, effect_inhibition_changed, attribute_changed, attribute_added, attribute_removed, tag_gained, tag_lost, tag_count_changed, ability_block_added, ability_block_removed, asc_initialized), the subject it happened to, the before and after rows, and a sentence saying what it means - an attribute whose current value moved while its base did not is reported as a modifier rather than as a failed write. Time is not counted as a change: effects present in both come back under stillActiveEffects with their remaining time on each side, and the gap is reported once as timeElapsedSeconds. Comparing two different actors is allowed and flagged. A pure read over snapshots you already have; to take the later reading and diff it in one call use capture_gas_state with compareWith. Params: beforeId OR beforeSnapshot, afterId OR afterSnapshot", "compare_gas_states", (p) => ({ beforeId: p.beforeId, beforeSnapshot: p.beforeSnapshot, afterId: p.afterId, afterSnapshot: p.afterSnapshot })),
    list_gas_snapshots:  bp("read", "List the GAS snapshots this editor session holds, oldest first, with the actor, world, capture time and per-section counts. Pass actorPath to narrow to one actor, or includeSnapshots to get the full bodies back. Params: actorPath?, includeSnapshots?", "list_gas_snapshots", (p) => ({ actorPath: p.actorPath, includeSnapshots: p.includeSnapshots })),
    delete_gas_snapshot: bp("mutate", "Drop one stored GAS snapshot, returning its contents first so nothing is lost: the returned object can be passed straight back to compare_gas_states as beforeSnapshot. Idempotent: an id that is not stored reports alreadyDeleted=true. Params: snapshotId", "delete_gas_snapshot", (p) => ({ snapshotId: p.snapshotId })),
    ...epicActions,
  },
  undefined,
  {
    ...epicSchema,
    blueprintPath: z.string().optional(),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    // Read by the create_* handlers in this category and undeclared until now,
    // so a caller asking to be told about a collision had the parameter
    // stripped and got the silent "skip" default instead.
    onConflict: z.string().optional().describe("create_attribute_set / create_ability / create_effect / create_cue: skip (default, returns the existing asset) or error when the asset already exists"),
    componentName: z.string().optional(),
    attributeSetPath: z.string().optional(),
    attributeName: z.string().optional(),
    defaultValue: z.number().optional(),
    parentClass: z.string().optional(),
    abilityPath: z.string().optional(),
    ability_tags: z.array(z.string()).optional(),
    cancel_abilities_with_tag: z.array(z.string()).optional(),
    block_abilities_with_tag: z.array(z.string()).optional(),
    activation_required_tags: z.array(z.string()).optional(),
    activation_blocked_tags: z.array(z.string()).optional(),
    effectPath: z.string().optional(),
    attribute: z.string().optional(),
    operation: z.string().optional(),
    magnitude: z.number().optional(),
    durationPolicy: z.string().optional(),
    cueType: z.string().optional(),
    // Runtime GAS control (apply_effect / set_attribute / get_attribute)
    actorLabel: z.string().optional().describe("Live actor label/name for runtime GAS actions"),
    effectClass: z.string().optional().describe("apply_effect: GameplayEffect content path or class name"),
    abilityClass: z.string().optional().describe("grant_ability / revoke_ability / trace_ability_activation: GameplayAbility Blueprint path, generated class path, or native class name"),
    inputId: z.number().optional().describe("grant_ability: InputID for the spec (default -1, meaning unbound)"),
    activate: z.boolean().optional().describe("trace_ability_activation: also call TryActivateAbility, to prove the verdict rather than predict it"),
    pieInstance: z.number().optional().describe("Which PIE world to target when world='pie': 0 = server/primary, 1..N = clients"),
    level: z.number().optional().describe("apply_effect: effect level (default 1)"),
    setByCaller: z.record(z.number()).optional().describe("apply_effect: SetByCaller magnitudes keyed by gameplay tag or name"),
    effectHandle: z.string().optional().describe("remove_effect: the active-effect handle apply_effect reported, as the string it came back as. The precise selector - it removes exactly the effect one apply_effect call added, where effectClass removes every active effect of that class"),
    stacksToRemove: z.number().optional().describe("remove_effect: how many stacks to take off (default -1, meaning remove the whole effect regardless of stack count)"),
    value: z.number().optional().describe("set_attribute: new base value"),
    world: z.string().optional().describe("Runtime world scope: auto (default) | pie | editor"),
    attributeSet: z.string().optional().describe("set_asc_defaults / init_asc: AttributeSet content path or class name"),
    initDataTable: z.string().optional().describe("set_asc_defaults: optional DataTable of starting attribute values"),
    actorPath: z.string().optional().describe("Full actor object path. The unambiguous selector for every runtime GAS action, and it wins over actorLabel when both are given. Editor labels are NOT unique, and a label matching several actors is refused with the candidates rather than resolved at random (#956/#983)"),
    // String rather than z.enum for the same reason as inputEvent below: the
    // handler rejects an unknown valueType and names both, and a strict enum
    // replaced that with a transport-level schema error.
    valueType: z.string().optional().describe("set_live_attribute_value: current | base. \"current\" (default) writes the attribute data in place; \"base\" writes through the ASC aggregator (#956)"),
    registerOwnerSets: z.boolean().optional().describe("get/set_live_attribute_value: register the actor's own attribute set subobjects on its ASC when it has none, the way BeginPlay would. Default true; false makes the call a strict read of what is already registered (#956)"),

    // -- Input binding (bind_ability_input / clear_ability_input / send_ability_input)
    // Deliberately a string, not z.enum. The MCP SDK validates arguments
    // BEFORE the tool callback runs, so a strict enum makes a typo fail at the
    // transport with a schema error, and the handler's own message, which names
    // all four valid values, never reaches the caller. The handler validates it
    // and says what is valid, which is the answer a caller can act on.
    inputEvent: z.string().optional().describe("send_ability_input: which input event to deliver: pressed | released | confirm | cancel. pressed/released address an inputId; confirm/cancel reach targeting actors and take none"),

    // -- Gameplay cues (add_effect_cue / remove_effect_cue / validate_cue_coverage)
    cueTag: z.string().optional().describe("add_effect_cue / remove_effect_cue: the GameplayCue tag. It has to be registered, and it has to sit under the GameplayCue root to be routed at all"),
    minLevel: z.number().optional().describe("add_effect_cue: lowest effect level this cue covers, used to normalise the magnitude handed to the notify"),
    maxLevel: z.number().optional().describe("add_effect_cue: highest effect level this cue covers. Equal min and max means the cue always gets a normalised magnitude of 1"),
    magnitudeAttribute: z.string().optional().describe("add_effect_cue: attribute the cue takes its magnitude from ('SetName.Attribute'), instead of the effect level"),
    directory: z.string().optional().describe("validate_cue_coverage: content path to scan, default /Game. Native effects live under /Script and are only in scope when the filter allows it"),
    maxEffects: z.number().optional().describe("validate_cue_coverage: cap on effect classes scanned, default 500"),

    // -- Attribute audit (audit_attributes)
    probeClamping: z.boolean().optional().describe("audit_attributes: measure an existing clamp by calling the set's own PreAttributeChange with extreme values instead of guessing. Needs a live registered set (actorLabel/actorPath), because the probe runs project code that may read its owning ASC. Default false"),

    // -- Snapshots (capture_gas_state / compare_gas_states / list / delete)
    compareWith: z.string().optional().describe("capture_gas_state: snapshot id to diff this capture against, so the second half of a capture-act-compare loop is one call. A missing id is a warning on the result, not a failure: the capture is kept"),
    snapshotId: z.string().optional().describe("capture_gas_state: id to store under, generated when omitted. delete_gas_snapshot: the id to drop"),
    includeSnapshots: z.boolean().optional().describe("list_gas_snapshots: return the full snapshot bodies rather than a summary row each"),
    beforeId: z.string().optional().describe("compare_gas_states: snapshot id of the earlier reading. Named beforeId rather than before because the schema reader treats bare 'before' as prose and would leave it undocumented"),
    afterId: z.string().optional().describe("compare_gas_states: snapshot id of the later reading"),
    beforeSnapshot: z.record(z.unknown()).optional().describe("compare_gas_states: the earlier snapshot object itself, for a comparison that has to survive an editor restart the id store does not"),
    afterSnapshot: z.record(z.unknown()).optional().describe("compare_gas_states: the later snapshot object itself"),
  },
);
