import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Vec3 } from "../schemas.js";

export const landscapeTool: ToolDef = categoryTool(
  "landscape",
  "Landscape terrain: info, layers, sculpting, weight painting, materials, splines, proxies.",
  {
    get_info:          bp("Get landscape setup", "get_landscape_info"),
    list_layers:       bp("List paint layers", "list_landscape_layers"),
    sample:            bp("Sample height/layers. Params: x, y", "sample_landscape"),
    sculpt:            bp("Raise, lower or flatten terrain with a circular brush. mode=raise|lower|flatten; amount is world centimetres at full strength (raise/lower), and flatten pulls toward the height under the brush centre. falloff (0..1) is the smoothstepped soft edge. Runs in one transaction and leaves the level dirty and unsaved. Writes into an edit layer (editLayer by name, else editLayerIndex, default 0) - required on UE 5.8, where a write without one is regenerated away by the layer system. Params: center ({x,y} world space), radius (default 500), mode? (default raise), amount? (default 100), falloff? (default 0.5), actorLabel?, editLayer?, editLayerIndex?, maxVertices? (#742)", "sculpt_landscape", (p) => ({ center: p.center, radius: p.radius, mode: p.mode, amount: p.amount, falloff: p.falloff, actorLabel: p.actorLabel, editLayer: p.editLayer, editLayerIndex: p.editLayerIndex, maxVertices: p.maxVertices })),
    paint_layer:       bp("Paint a weight layer with a circular brush. The layer must already have a LayerInfo on this landscape (see add_layer_info) - an unregistered name errors and lists the layers that ARE registered instead of silently painting nothing. Weights are written as given - the engine no longer renormalises other layers for you, so set them explicitly if they must sum to 1. Writes into an edit layer (editLayer by name, else editLayerIndex, default 0). Params: layerName, center ({x,y} world space), radius (default 500), strength? (0..1, default 1), falloff? (default 0.5), actorLabel?, editLayer?, editLayerIndex?, maxVertices? (#742)", "paint_landscape_layer", (p) => ({ layerName: p.layerName, center: p.center, radius: p.radius, strength: p.strength, falloff: p.falloff, actorLabel: p.actorLabel, editLayer: p.editLayer, editLayerIndex: p.editLayerIndex, maxVertices: p.maxVertices })),
    list_splines:      bp("Read landscape splines", "list_landscape_splines"),
    get_component:     bp("Inspect component. Params: componentIndex", "get_landscape_component"),
    set_material:      bp("Set landscape material. Params: materialPath", "set_landscape_material"),
    add_layer_info:    bp("Register paint layer (creates LayerInfo asset + binds to active landscape). Params: layerName, packagePath?", "add_landscape_layer_info"),
    create_layer_info: bp("Standalone LayerInfo asset creation - no landscape required. Params: layerName, name? (default LI_<layerName>), packagePath? (default /Game/Landscape/LayerInfos), physMaterial? (asset path), hardness? (#251)", "create_landscape_layer_info", (p) => ({ layerName: p.layerName, name: p.name, packagePath: p.packagePath, physMaterial: p.physMaterial, hardness: p.hardness, onConflict: p.onConflict })),
    create:            bp("Spawn a new ALandscape with a flat heightmap. Defaults match the Editor's Landscape Mode 'create new' (8x8 components, 63 quads/subsection, 2 subsections/component = 1016x1016 quads). Params: location? (Vec3), scale? (Vec3, default 100,100,100), componentCountX? (default 8), componentCountY? (default 8), subsectionSizeQuads? (one of 7|15|31|63|127|255, default 63), numSubsections? (1|2, default 2), heightOffset? (uint16, default 32768 = mid-elevation), label? (#303)", "create_landscape", (p) => ({ location: p.location, scale: p.scale, componentCountX: p.componentCountX, componentCountY: p.componentCountY, subsectionSizeQuads: p.subsectionSizeQuads, numSubsections: p.numSubsections, heightOffset: p.heightOffset, label: p.label })),
    get_material_usage_summary: bp("Per-proxy summary: landscape/hole material paths + component/grass/nanite counts (#150)", "get_landscape_material_usage_summary"),
    list_proxies:      bp("Enumerate loaded World Partition LandscapeStreamingProxy actors with per-proxy worldBounds (origin/extent), plus loadedProxies + parentLandscapes counts. Unloaded proxies are not spawned as actors, so only loaded ones appear - use this to confirm a proxy is streamed in before trusting a layer/height readback (#733)", "list_landscape_proxies"),
    find_proxy_at:     bp("Resolve which loaded LandscapeStreamingProxy covers a world X/Y. Returns found/loaded + label, or loaded:false when the covering proxy is streamed out (so a 0-weight readback there is ambiguous, not real). Params: worldX, worldY (#733)", "find_landscape_proxy_at", (p) => ({ worldX: p.worldX, worldY: p.worldY })),
  },
  undefined,
  {
    x: z.number().optional(), y: z.number().optional(),
    worldX: z.number().optional().describe("find_proxy_at: world-space X (#733)"),
    worldY: z.number().optional().describe("find_proxy_at: world-space Y (#733)"),
    radius: z.number().optional(), strength: z.number().optional(),
    center: z.record(z.number()).optional().describe("sculpt/paint_layer: brush centre {x, y} in world space (#742)"),
    mode: z.string().optional().describe("sculpt: raise | lower | flatten (#742)"),
    amount: z.number().optional().describe("sculpt: world centimetres to move at full brush strength (#742)"),
    actorLabel: z.string().optional().describe("sculpt/paint_layer: which Landscape actor, when the level has more than one (#742)"),
    editLayer: z.string().optional().describe("sculpt/paint_layer: edit layer NAME to write into; without one the write targets the merged heightmap and is regenerated away (#742)"),
    editLayerIndex: z.number().optional().describe("sculpt/paint_layer: edit layer index (default 0) when editLayer is not given (#742)"),
    maxVertices: z.number().optional().describe("sculpt/paint_layer: refuse a brush covering more than this many vertices (default 4,000,000) (#742)"),
    falloff: z.number().optional(),
    layerName: z.string().optional(),
    materialPath: z.string().optional(),
    filePath: z.string().optional(),
    componentIndex: z.number().optional(),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    physMaterial: z.string().optional(),
    hardness: z.number().optional(),
    onConflict: z.string().optional(),
    location: Vec3.optional(),
    scale: Vec3.optional(),
    componentCountX: z.number().optional(),
    componentCountY: z.number().optional(),
    subsectionSizeQuads: z.number().optional(),
    numSubsections: z.number().optional(),
    heightOffset: z.number().optional(),
    label: z.string().optional(),
  },
);
