import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Vec3, Rotator, Color } from "../schemas.js";

export const levelTool: ToolDef = categoryTool(
  "level",
  "Level actors, selection, components, level management, volumes, lights, and splines.",
  {
    get_outliner:       bp("List actors. Params: classFilter?, nameFilter?, world? (editor|pie|auto), limit?", "get_world_outliner"),
    place_actor:        bp("Spawn actor. Pass world:pie to spawn into the running PIE world (#585). Params: actorClass, label?, location?, rotation?, scale?, staticMesh?, material?, world? (editor|pie)", "place_actor"),
    delete_actor:       bp("Remove actor. Params: actorLabel", "delete_actor"),
    get_actor_details:  bp("Inspect actor. Params: actorLabel OR actorPath, includeProperties?, propertyName?, world? (editor|pie)", "get_actor_details"),
    move_actor:         bp("Transform actor. Pass world:pie to move a live PIE actor (resolves labels/names from get_outliner {world:pie}) (#586). Params: actorLabel, location?, rotation?, scale?, world? (editor|pie)", "move_actor", (p) => ({ actorLabel: p.actorLabel, location: p.location, rotation: p.rotation, scale: p.scale, world: p.world })),
    aim_actor_at:       bp("Rotate an actor so its forward (+X) points at a target. Params: actorLabel, targetPoint (Vec3) OR targetActor (label), roll? (default 0), world? (editor|pie) (#566)", "aim_actor_at", (p) => ({ actorLabel: p.actorLabel, target: p.targetPoint, targetActor: p.targetActor, roll: p.roll, world: p.world })),
    nav_project_point:  bp("Project a world point onto the navmesh. Returns onNavMesh + projectedLocation. Params: point (Vec3), extent? (Vec3, default 100), world? (editor|pie) (#585)", "nav_project_point", (p) => ({ point: p.point, extent: p.extent, world: p.world })),
    select:             bp("Select actors. Params: actorLabels[]", "select_actors"),
    get_selected:       bp("Get selection", "get_selected_actors"),
    add_component:      bp("Add component to actor. Params: actorLabel, componentClass, componentName?", "add_component_to_actor"),
    remove_component:   bp("Remove instance component from a level actor by name. Idempotent: returns alreadyDeleted=true if no matching component exists. Params: actorLabel, componentName (#426)", "remove_component_from_actor", (p) => ({ actorLabel: p.actorLabel, componentName: p.componentName })),
    set_component_property: bp("Set component prop. Pass value=null to clear a TObjectPtr/SoftObject/WeakObject/UClass/Interface reference (#420). Resolves inherited/SCS components on placed Blueprint instances case-insensitively, and refreshes the scene transform after RelativeLocation/RelativeRotation/RelativeScale3D writes (#539). Params: actorLabel, componentName, propertyName, value", "set_component_property"),
    get_component_details: bp("Read a placed actor's component transforms. With componentName returns that component's relative+world location/rotation/scale, class, and attach parent; without it lists every component. With includeValues=true also dumps arbitrary UPROPERTY values (custom fields, CharacterMovement MaxWalkSpeed, etc.); world='pie' reads the live PIE instance (#539/#584). Params: actorLabel, componentName?, includeValues?, propertyNames? (filter), world? (editor|pie)", "get_component_details", (p) => ({ actorLabel: p.actorLabel, componentName: p.componentName, includeValues: p.includeValues, propertyNames: p.propertyNames, world: p.world })),
    get_current:        bp("Get current level name and path", "get_current_level"),
    load:               bp("Load level. Params: levelPath", "load_level"),
    save:               bp("Save current level", "save_current_level"),
    list:               bp("List levels. Params: directory?, recursive?", "list_levels"),
    create:             bp("Create new level. Params: levelPath?, templateLevel?", "create_new_level"),
    spawn_volume:       bp("Place volume. Params: volumeType, location?, extent?, label?", "spawn_volume"),
    list_volumes:       bp("List volumes. Params: volumeType?", "list_volumes"),
    set_volume_properties: bp("Edit volume. Params: actorLabel, properties", "set_volume_properties"),
    spawn_light:        bp("Place light. Params: lightType (point|spot|directional|rect|sky), location?, rotation?, intensity?, color? ({r,g,b} 0-255), mobility? (static|stationary|movable; default movable so the light renders without a build), label? (#331/#310)", "spawn_light"),
    set_light_properties: bp("Edit a light OR SkyLight (intensity/color now work on SkyLight too, #608). Params: actorLabel, intensity?, color?, rotation? (DirectionalLight sun angle), mobility? (static|stationary|movable), recaptureSky?, volumetricScatteringIntensity?, sourceRadius? (point/spot), innerConeAngle?/outerConeAngle? (spot)", "set_light_properties"),
    set_fog_properties: bp("Edit ExponentialHeightFog incl. volumetric fog (#608). Params: actorLabel?, fogDensity?, fogHeightFalloff?, startDistance?, fogInscatteringColor?, enableVolumetricFog?, volumetricFogScatteringDistribution?, volumetricFogExtinctionScale?, volumetricFogDistance?, volumetricFogAlbedo?", "set_fog_properties"),
    get_actors_by_class: bp("List actors by class. Matches Blueprint subclasses of a native base via IsChildOf when className resolves to a UClass (short name, /Script path, or BP class path), else falls back to name-substring. Each actor includes location/rotation/scale. Params: className, world? (editor|pie), matchSubclasses? (default true), includeTransforms? (default true) (#675)", "get_actors_by_class", (p) => ({ className: p.className, world: p.world, matchSubclasses: p.matchSubclasses, includeTransforms: p.includeTransforms })),
    get_actors_by_component_class: bp("List actors that own a component of a given class (exact or substring match). Returns each actor plus its matchedComponents. Params: componentClass, world? (editor|pie) (#582)", "get_actors_by_component_class", (p) => ({ componentClass: p.componentClass, className: p.className, world: p.world })),
    count_actors_by_class: bp("Histogram of actor classes in the level (sorted desc). Params: world? (editor|pie), topN? (#146)", "count_actors_by_class", (p) => ({ world: p.world, topN: p.topN })),
    get_runtime_virtual_texture_summary: bp("List RuntimeVirtualTextureVolume actors + their bound VirtualTexture assets (#150)", "get_runtime_virtual_texture_summary"),
    set_water_body_property: bp("Set a property on an actor's WaterBodyComponent (ShapeDilation, WaterLevel, etc.). Params: actorLabel, propertyName, value. Requires Water plugin. For spline edits use level(set_spline_points) (#151)", "set_water_body_property", (p) => ({ actorLabel: p.actorLabel, propertyName: p.propertyName, value: p.value })),
    build_lighting:     bp("Build lights. Params: quality?", "build_lighting"),
    get_spline_info:    bp("Read a spline component's points, closedLoop, length, and per-point tangents/types. Works in editor or PIE (#553). Optional componentName picks a specific (custom) spline; projectPoint (Vec3) returns the closest location, inputKey, distanceAlongSpline, distanceToSpline, and tangent (#555). Params: actorLabel, componentName?, world? (editor|pie), projectPoint?", "get_spline_info", (p) => ({ actorLabel: p.actorLabel, componentName: p.componentName, world: p.world, projectPoint: p.projectPoint })),
    set_spline_points:  bp("Set spline points. Params: actorLabel, points[], closedLoop?", "set_spline_points"),
    set_actor_material: bp("Set material on actor. Params: actorLabel, materialPath, slotIndex?", "set_actor_material"),
    get_world_settings: bp("Read world settings (GameMode, KillZ, gravity, etc.)", "get_world_settings"),
    set_world_settings: bp("Set world settings. Params: defaultGameMode?, killZ?, globalGravityZ?, enableWorldBoundsChecks?", "set_world_settings"),
    get_actor_bounds:   bp("Get actor AABB. Params: actorLabel. Returns origin + extent (#188)", "get_actor_bounds"),
    get_component_tree: bp("Deep component-tree dump for an actor. Returns per-component: name, class, attachParent, attachSocket, mobility, visibility, relative+world transforms, tags. For PrimitiveComponents adds collisionProfile/collisionEnabled/bounds/castShadow. For StaticMeshComponent adds staticMesh + materials[]. For SkeletalMeshComponent adds skeletalMesh + skeleton + materials[]. For NiagaraComponent adds niagara{asset,active,visible} and for AudioComponent audio{sound,playing} - runtime FX state in PIE (#581). Params: actorLabel | actorPath, world? (editor|pie), componentClass? (substring filter), includeProperties? (dump UPROPERTY name/type/value per component) (#240/#241/#302/#320/#370/#353/#581)", "get_component_tree", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, world: p.world, componentClass: p.componentClass, includeProperties: p.includeProperties })),
    get_relative_transform: bp("Compute target's transform in reference's local space (location/rotation/scale). Common dungeon/calibration workflow. Params: target (actor label), reference (actor label), world? (#386/#387)", "get_relative_transform", (p) => ({ targetLabel: p.target ?? p.targetLabel, referenceLabel: p.reference ?? p.referenceLabel, target: p.target, reference: p.reference, world: p.world })),
    resolve_actor:      bp("Resolve internal/runtime actor name to editor label. Params: internalName (e.g. StaticMeshActor_141). Returns actorLabel, actorPath, className, location (#178)", "resolve_actor"),
    set_actor_property: bp("Set per-instance UPROPERTY on a level actor. Params: actorLabel ('WorldSettings' targets the world settings actor), propertyName (dotted paths like 'Foo.Bar' supported), value (string/number/bool/object/array; a label string resolves to an AActor* ref, and a JSON array of labels populates a TArray of actor refs #538), force? (bypass EditDefaultsOnly), world? (editor|pie) (#202/#230)", "set_actor_property", (p) => ({ actorLabel: p.actorLabel, propertyName: p.propertyName, value: p.value, force: p.force, world: p.world })),
    read_actor_motion: bp("Snapshot motion telemetry for one or many actors: location, rotation, velocity, scale, angularVelocity (when simulating physics), grounded + distanceToGround (downward 200u trace). Defaults to the PIE world with editor fallback. Loop at your sample interval for long telemetry probes. Params: actorLabel? OR actorLabels (string[]), world? ('pie'|'editor') (#453)", "read_actor_motion", (p) => ({ actorLabel: p.actorLabel, actorLabels: p.actorLabels, world: p.world })),
    add_hismc_instances: bp("Bulk-add transforms to a HISMC / ISMC component on an actor (Python add_instance crashes on UE 5.7; this is the C++ path). Params: actorLabel, componentName? (default: first ISMC/HISMC found), transforms ([{location: {x,y,z}, rotation?: {pitch,yaw,roll}, scale?: {x,y,z}}]), worldSpace? (default true) (#434)", "add_hismc_instances", (p) => ({ actorLabel: p.actorLabel, componentName: p.componentName, transforms: p.transforms, worldSpace: p.worldSpace })),
    get_instance_transforms: bp("Read every instance transform on an actor's ISMC/HISMC. Params: actorLabel, componentName? (default first), worldSpace? (default true). Returns instances[{index, location, rotation, scale}] (#697)", "get_instance_transforms", (p) => ({ actorLabel: p.actorLabel, componentName: p.componentName, worldSpace: p.worldSpace })),
    update_instance_transform: bp("Update a single ISMC/HISMC instance by index; unspecified location/rotation/scale are preserved. Params: actorLabel, componentName?, index, location?, rotation?, scale?, worldSpace? (default true) (#697)", "update_instance_transform", (p) => ({ actorLabel: p.actorLabel, componentName: p.componentName, index: p.index, location: p.location, rotation: p.rotation, scale: p.scale, worldSpace: p.worldSpace })),
    remove_instance: bp("Remove a single ISMC/HISMC instance by index. Params: actorLabel, componentName?, index (#697)", "remove_instance", (p) => ({ actorLabel: p.actorLabel, componentName: p.componentName, index: p.index })),
    set_nanite_settings: bp("Enable/disable + force-build Nanite on a UStaticMesh asset (rebuilds render data immediately, not on next cook). Params: assetPath, enabled? (default true), positionPrecision? (#696)", "set_nanite_settings", (p) => ({ assetPath: p.assetPath, enabled: p.enabled, positionPrecision: p.positionPrecision })),
    get_nanite_info: bp("Read a UStaticMesh's Nanite state (naniteEnabled, positionPrecision, numLODs). Params: assetPath (#696)", "get_nanite_info", (p) => ({ assetPath: p.assetPath })),
    add_post_process_blendable: bp("Add a material blendable (post-process material or MID, e.g. a toon/outline pass) to a PostProcessVolume's WeightedBlendables. Params: actorLabel (the PPV), materialPath, weight? (default 1) (#666)", "add_post_process_blendable", (p) => ({ actorLabel: p.actorLabel, materialPath: p.materialPath, weight: p.weight })),
    export_actor_fbx: bp("Export an actor's skeletal/static mesh to FBX and write a metadata sidecar JSON (actor transform, mesh, materials, skeleton) for a downstream bridge (e.g. MetaTailor). Params: actorLabel, outputPath (.fbx). Returns fbx + metadata paths (#637)", "export_actor_fbx", (p) => ({ actorLabel: p.actorLabel, outputPath: p.outputPath })),
    spawn_skeletal_mesh_actor: bp("Spawn a SkeletalMeshActor for visual/deform verification. Optional per-slot materials and single-node animation preview (animSequence + loop). Returns actorLabel + boxExtent. Params: skeletalMesh, label?, location?, rotation?, scale?, materials? (path[]), animSequence?, loop? (#679/#677)", "spawn_skeletal_mesh_actor", (p) => ({ skeletalMesh: p.skeletalMesh, label: p.label, location: p.location, rotation: p.rotation, scale: p.scale, materials: p.materials, animSequence: p.animSequence, loop: p.loop, onConflict: p.onConflict })),
    delete_actors: bp("Bulk-delete actors. Params: at least one of labelPrefix, className, tag; dryRun? to preview. Returns matched/deleted/labels (#220)", "delete_actors", (p) => ({ labelPrefix: p.labelPrefix, className: p.className, tag: p.tag, dryRun: p.dryRun })),
    add_actor_tag: bp("Append a tag to an actor's Tags array. Params: actorLabel, tag (#219)", "add_actor_tag", (p) => ({ actorLabel: p.actorLabel, tag: p.tag })),
    remove_actor_tag: bp("Remove a tag from an actor's Tags array. Params: actorLabel, tag (#219)", "remove_actor_tag", (p) => ({ actorLabel: p.actorLabel, tag: p.tag })),
    set_actor_tags: bp("Replace an actor's Tags array. Params: actorLabel, tags[] (#219)", "set_actor_tags", (p) => ({ actorLabel: p.actorLabel, tags: p.tags })),
    list_actor_tags: bp("List an actor's Tags. Params: actorLabel (#219)", "list_actor_tags", (p) => ({ actorLabel: p.actorLabel })),
    attach_actor: bp("Attach actor as child. Params: childLabel, parentLabel, attachRule? (KeepWorld|KeepRelative|SnapToTarget; default KeepWorld), socketName? (#205)", "attach_actor", (p) => ({ childLabel: p.childLabel, parentLabel: p.parentLabel, attachRule: p.attachRule, socketName: p.socketName })),
    detach_actor: bp("Detach actor from parent. Params: childLabel (#205)", "detach_actor", (p) => ({ childLabel: p.childLabel })),
    set_actor_mobility: bp("Set actor root component Mobility. Params: actorLabel, mobility (static|stationary|movable) (#205)", "set_actor_mobility", (p) => ({ actorLabel: p.actorLabel, mobility: p.mobility })),
    get_current_edit_level: bp("Read the active edit-target sub-level (#204)", "get_current_edit_level"),
    set_current_edit_level: bp("Set the active edit-target sub-level so subsequent spawns land in it. Params: levelName (e.g. SubLevel_A) (#204)", "set_current_edit_level", (p) => ({ levelName: p.levelName, levelPath: p.levelPath })),
    list_streaming_sublevels: bp("List streaming sub-levels with transform + initially-loaded/visible flags (#206)", "list_streaming_sublevels"),
    add_streaming_sublevel: bp("Add a streaming sub-level. Params: levelPath, streamingClass? (LevelStreamingDynamic|LevelStreamingAlwaysLoaded), location?, initiallyLoaded?, initiallyVisible? (#206)", "add_streaming_sublevel", (p) => ({ levelPath: p.levelPath, streamingClass: p.streamingClass, location: p.location, initiallyLoaded: p.initiallyLoaded, initiallyVisible: p.initiallyVisible })),
    remove_streaming_sublevel: bp("Remove a streaming sub-level. Params: levelName | levelPath (#206)", "remove_streaming_sublevel", (p) => ({ levelName: p.levelName, levelPath: p.levelPath })),
    set_streaming_sublevel_properties: bp("Update sub-level transform/visibility flags. Params: levelName | levelPath, location?, initiallyLoaded?, initiallyVisible?, editorVisible? (#206)", "set_streaming_sublevel_properties", (p) => ({ levelName: p.levelName, levelPath: p.levelPath, location: p.location, initiallyLoaded: p.initiallyLoaded, initiallyVisible: p.initiallyVisible, editorVisible: p.editorVisible })),
    spawn_grid: bp("Batch-spawn StaticMeshActors on a grid. Params: staticMesh, min, max (Vec3 bounds), countX?, countY?, countZ?, jitter?, labelPrefix? (#203)", "spawn_grid", (p) => ({ staticMesh: p.staticMesh, min: p.min, max: p.max, countX: p.countX, countY: p.countY, countZ: p.countZ, jitter: p.jitter, labelPrefix: p.labelPrefix })),
    batch_translate: bp("Translate a set of actors by an offset. Params: offset (Vec3), actorLabels[] OR tag (#203)", "batch_translate", (p) => ({ offset: p.offset, actorLabels: p.actorLabels, tag: p.tag })),
    place_actors_batch: bp("Bulk-spawn StaticMeshActors with per-instance mesh + transform. Params: actors[]: [{staticMesh, location?, rotation?, scale?, label?}]. Mesh loads cached per path. Returns spawned/failedMesh/failedSpawn counts + labels (#264)", "place_actors_batch", (p) => ({ actors: p.actors })),
    line_trace: bp("Line trace in the editor world. Returns hit + actorLabel/actorClass/componentName/componentClass/location/impactPoint/normal/distance/faceIndex/boneName/physicalMaterial. Params: start (Vec3), end? (Vec3) OR direction? (Vec3) + distance? (default 200000), ignoreActors? (array of labels) (#420)", "line_trace", (p) => ({ start: p.start, end: p.end, direction: p.direction, distance: p.distance, ignoreActors: p.ignoreActors })),
    snap_actor_to_floor: bp("Snap an actor's bounds-bottom to the first downward line-trace hit. Equivalent of the End-key shortcut, works on arbitrary geometry (not just Landscape). Params: actorLabel, floorOffset? (added to impact Z, default 0), maxDistance? (default 100000) (#419)", "snap_actor_to_floor", (p) => ({ actorLabel: p.actorLabel, floorOffset: p.floorOffset, maxDistance: p.maxDistance })),
  },
  undefined,  // actionDocs auto-generated from descriptions
  {
    actorLabel: z.string().optional(), actorLabels: z.array(z.string()).optional(),
    actorClass: z.string().optional(), label: z.string().optional(),
    location: Vec3.optional(),
    rotation: Rotator.optional(),
    scale: Vec3.optional(),
    targetPoint: Vec3.optional().describe("aim_actor_at: world-space point to look at (alternative to targetActor)"),
    projectPoint: Vec3.optional().describe("get_spline_info: world-space point to project onto the spline (#555)"),
    targetActor: z.string().optional().describe("aim_actor_at: label of the actor to look at (alternative to targetPoint)"),
    roll: z.number().optional().describe("aim_actor_at: roll angle in degrees (default 0)"),
    properties: z.record(z.unknown()).optional(),
    classFilter: z.string().optional(), nameFilter: z.string().optional(),
    componentClass: z.string().optional(), componentName: z.string().optional(),
    transforms: z.array(z.record(z.unknown())).optional().describe("add_hismc_instances transform list (#434)"),
    worldSpace: z.boolean().optional().describe("add_hismc_instances/instance ops: treat transforms as world-space (default true) (#434)"),
    index: z.number().optional().describe("update_instance_transform/remove_instance: instance index (#697)"),
    assetPath: z.string().optional().describe("set_nanite_settings/get_nanite_info: UStaticMesh path (#696)"),
    enabled: z.boolean().optional().describe("set_nanite_settings: enable Nanite (default true) (#696)"),
    positionPrecision: z.number().optional().describe("set_nanite_settings: Nanite position precision (#696)"),
    outputPath: z.string().optional().describe("export_actor_fbx: output .fbx path (#637)"),
    skeletalMesh: z.string().optional().describe("spawn_skeletal_mesh_actor: USkeletalMesh path (#679)"),
    materials: z.array(z.string()).optional().describe("spawn_skeletal_mesh_actor: per-slot material paths (#679)"),
    animSequence: z.string().optional().describe("spawn_skeletal_mesh_actor: single-node preview animation (#679)"),
    loop: z.boolean().optional().describe("spawn_skeletal_mesh_actor: loop the preview animation (#679)"),
    onConflict: z.string().optional().describe("spawn_skeletal_mesh_actor: label conflict policy (skip|error)"),
    includeValues: z.boolean().optional().describe("get_component_details: dump arbitrary UPROPERTY values (#584)"),
    propertyNames: z.array(z.string()).optional().describe("get_component_details: restrict includeValues to these property names (#584)"),
    matchSubclasses: z.boolean().optional().describe("get_actors_by_class: match Blueprint subclasses via IsChildOf (default true) (#675)"),
    includeTransforms: z.boolean().optional().describe("get_actors_by_class: include per-actor location/rotation/scale (default true) (#675)"),
    propertyName: z.string().optional(), value: z.unknown().optional(),
    levelPath: z.string().optional(), templateLevel: z.string().optional(),
    directory: z.string().optional(), recursive: z.boolean().optional(),
    volumeType: z.string().optional(),
    extent: Vec3.optional(),
    point: Vec3.optional().describe("nav_project_point: world-space point to project onto the navmesh (#585)"),
    lightType: z.string().optional(), intensity: z.number().optional(),
    color: Color.optional(),
    temperature: z.number().optional(), castShadows: z.boolean().optional(),
    attenuationRadius: z.number().optional(),
    innerConeAngle: z.number().optional(), outerConeAngle: z.number().optional(),
    quality: z.string().optional(),
    points: z.array(Vec3).optional(),
    closedLoop: z.boolean().optional(),
    staticMesh: z.string().optional().describe("Asset path for static mesh (e.g. /Engine/BasicShapes/Cube.Cube)"),
    material: z.string().optional().describe("Asset path for material to apply at slot 0"),
    materialPath: z.string().optional().describe("Material asset path for set_actor_material"),
    slotIndex: z.number().optional().describe("Material slot index (default 0)"),
    actorPath: z.string().optional().describe("Full actor object path; alternative to actorLabel"),
    includeProperties: z.boolean().optional().describe("Include reflected UPROPERTY values in get_actor_details"),
    world: z.string().optional().describe("World scope: editor (default) or pie"),
    className: z.string().optional().describe("Class name filter for get_actors_by_class"),
    topN: z.number().optional().describe("Limit for count_actors_by_class result"),
    fogDensity: z.number().optional(),
    fogHeightFalloff: z.number().optional(),
    startDistance: z.number().optional(),
    fogInscatteringColor: Color.optional(),
    recaptureSky: z.boolean().optional(),
    volumetricScatteringIntensity: z.number().optional().describe("set_light_properties: light/skylight volumetric scattering intensity (#608)"),
    sourceRadius: z.number().optional().describe("set_light_properties: point/spot light source radius (#608)"),
    enableVolumetricFog: z.boolean().optional().describe("set_fog_properties: enable volumetric fog (#608)"),
    volumetricFogScatteringDistribution: z.number().optional().describe("set_fog_properties: volumetric fog scattering distribution (#608)"),
    volumetricFogExtinctionScale: z.number().optional().describe("set_fog_properties: volumetric fog extinction scale (#608)"),
    volumetricFogDistance: z.number().optional().describe("set_fog_properties: volumetric fog distance (#608)"),
    volumetricFogAlbedo: Color.optional().describe("set_fog_properties: volumetric fog albedo (#608)"),
    defaultGameMode: z.string().optional(),
    killZ: z.number().optional(),
    globalGravityZ: z.number().optional(),
    enableWorldBoundsChecks: z.boolean().optional(),
    internalName: z.string().optional().describe("Internal/runtime UObject name for resolve_actor (e.g. StaticMeshActor_141)"),
    target: z.string().optional().describe("Target actor label for get_relative_transform"),
    reference: z.string().optional().describe("Reference actor label for get_relative_transform"),
    start: Vec3.optional().describe("line_trace: ray start"),
    end: Vec3.optional().describe("line_trace: ray end (use this OR direction+distance)"),
    direction: Vec3.optional().describe("line_trace: ray direction (unit-normalized internally)"),
    distance: z.number().optional().describe("line_trace: ray length when direction is supplied (default 200000)"),
    ignoreActors: z.array(z.string()).optional().describe("line_trace: actor labels to skip"),
    floorOffset: z.number().optional().describe("snap_actor_to_floor: vertical offset added to impact Z"),
    maxDistance: z.number().optional().describe("snap_actor_to_floor: line-trace length downward (default 100000)"),
    force: z.boolean().optional().describe("set_actor_property: bypass EditDefaultsOnly to write per-instance overrides"),
    labelPrefix: z.string().optional().describe("delete_actors: actor label prefix filter"),
    tag: z.string().optional(),
    tags: z.array(z.string()).optional(),
    dryRun: z.boolean().optional().describe("delete_actors: report matches without deleting"),
    childLabel: z.string().optional(),
    parentLabel: z.string().optional(),
    attachRule: z.string().optional().describe("attach_actor: KeepWorld | KeepRelative | SnapToTarget"),
    socketName: z.string().optional(),
    mobility: z.string().optional().describe("set_actor_mobility: static | stationary | movable"),
    levelName: z.string().optional(),
    streamingClass: z.string().optional().describe("add_streaming_sublevel: LevelStreamingDynamic (default) | LevelStreamingAlwaysLoaded"),
    initiallyLoaded: z.boolean().optional(),
    initiallyVisible: z.boolean().optional(),
    editorVisible: z.boolean().optional().describe("set_streaming_sublevel_properties: editor viewport visibility"),
    min: Vec3.optional().describe("spawn_grid lower bound"),
    max: Vec3.optional().describe("spawn_grid upper bound"),
    countX: z.number().optional(),
    countY: z.number().optional(),
    countZ: z.number().optional(),
    jitter: z.number().optional().describe("spawn_grid: per-axis location jitter"),
    offset: Vec3.optional(),
    actors: z.array(z.object({
      staticMesh: z.string(),
      location: Vec3.optional(),
      rotation: Rotator.optional(),
      scale: Vec3.optional(),
      label: z.string().optional(),
    })).optional().describe("place_actors_batch: per-instance mesh+transform records"),
  },
);
