import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Color } from "../schemas.js";
import { PAGINATION_SCHEMA, paged } from "../pagination.js";
import { actions as epicActions, schema as epicSchema } from "./epic/material.generated.js";

export const materialTool: ToolDef = categoryTool(
  "material",
  "Materials: create, read, parameters, shading, textures, and graph authoring (expression nodes, connections).",
  {
    read:              bp("read", "Read material structure. Accepts a Material or a MaterialInstance; an instance answers with its lineage, shading setup and resolved parameters instead of a graph (#952). Params: assetPath", "read_material", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    list_parameters:   bp("read", "List parameters. On a MaterialInstance each entry carries the resolved value, the parent's defaultValue and whether this instance overrides it (#952). Params: assetPath", "list_material_parameters", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    set_parameter:     bp("mutate", "Set parameter on MaterialInstance. Params: assetPath, parameterName, parameterType? (scalar|vector|texture, auto-detected when omitted), value, association?. A vector/colour value may be passed as value OR color, shaped {r,g,b,a}, [r,g,b,a] or '(R=..,G=..,B=..,A=..)'. Saves the instance and returns readBack + saved so a set/verify round trip needs no second call (#952)", "set_material_parameter"),
    read_instance:     bp("read", "Read a MaterialInstanceConstant parent and override summary. Params: assetPath", "read_material_instance", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    set_instance_parent: bp("mutate", "Set a MaterialInstanceConstant parent. Params: assetPath, newParentPath (or parentPath)", "set_material_instance_parent", (p) => ({ assetPath: p.assetPath ?? p.materialPath, newParentPath: p.newParentPath ?? p.parentPath })),
    batch_set_instances: bp("mutate", "Batch reparent + reassign parameters across many Material Instances in one call. Params: instances[] = [{assetPath, parentPath?, parameters?:[{name, type (scalar|vector|texture), value}]}]. value: number (scalar), {r,g,b,a} (vector), or texture path (texture). Returns per-instance results (#594)", "batch_set_material_instances", (p) => ({ instances: p.instances })),
    clear_instance_parameters: bp("mutate", "Clear all MaterialInstanceConstant parameter overrides. Params: assetPath", "clear_material_instance_parameters", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    list_static_switches: bp("read", "List static switch parameters on a Material or MaterialInstance. Params: assetPath", "list_material_static_switches", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    set_static_switch: bp("mutate", "Set a MaterialInstanceConstant static switch parameter. Params: assetPath, parameterName, value, association?, parameterIndex?", "set_material_static_switch", (p) => ({ assetPath: p.assetPath ?? p.materialPath, parameterName: p.parameterName, value: p.value, association: p.association, parameterIndex: p.parameterIndex })),
    set_expression_value: bp("mutate", "Set a value on an expression node. Common typed knobs: value (constant/param default), texturePath (TextureSample/TextureSampleParameter2D default texture). Constant2Vector/3Vector/4Vector and VectorParameter all take value (or color) as {r,g,b,a}, {x,y,z,w}, [r,g,b,a] or '(R=..,G=..)'; Constant2Vector reads the first two components (#979). Saves the material and reports saved. A TextureCoordinate node takes uTiling, vTiling and coordinateIndex, which are separate top-level keys rather than anything inside `value`. For any OTHER UPROPERTY on the expression (e.g. SamplerType, SamplerSource, Group), pass propertyName + value to hit the generic reflection setter. Reports previousValue and rolls back to it where the previous value can be expressed in this action's own vocabulary. Params: materialPath, expressionIndex, value?, color?, texturePath?, uTiling?, vTiling?, coordinateIndex?, propertyName? (#663)", "set_expression_value"),
    set_custom_expression: bp("mutate", "Read/write a MaterialExpressionCustom (HLSL) node: code, named inputs[] (rebuilds input pins; wire them with connect_expressions targetInput=<name>), outputType (float1|float2|float3|float4|materialAttributes), description. Omit code/inputs to read. Add the node first via add_expression expressionType=Custom. Params: materialPath, expressionIndex, code?, inputs?, outputType?, description? (#617)", "set_custom_expression", (p) => ({ materialPath: p.materialPath ?? p.assetPath, expressionIndex: p.expressionIndex, code: p.code, inputs: p.inputs, outputType: p.outputType, description: p.description })),
    disconnect_property: bp("mutate", "Disconnect a material property input. Params: materialPath, property", "disconnect_material_property"),
    create_instance:   bp("mutate", "Create material instance. Params: parentPath, name?, packagePath?", "create_material_instance"),
    create:            bp("mutate", "Create material. Params: name, packagePath?", "create_material"),
    create_function:   bp("mutate", "Create a MaterialFunction asset. Params: name, packagePath? (default /Game/Materials/Functions), description? (#463)", "create_material_function", (p) => ({ name: p.name, packagePath: p.packagePath, description: p.description, onConflict: p.onConflict })),
    add_function_expression: bp("mutate", "Add an expression node to a MaterialFunction graph. Params: functionPath, expressionType (e.g. Constant3Vector, FunctionInput, FunctionOutput, If), positionX?, positionY?, inputName? (for FunctionInput), inputType? (Scalar|Vector2|Vector3|Vector4|Texture2D|TextureCube|StaticBool|MaterialAttributes), outputName? (for FunctionOutput) (#463)", "add_expression_in_function", (p) => ({ functionPath: p.functionPath ?? p.materialFunctionPath, expressionType: p.expressionType, positionX: p.positionX, positionY: p.positionY, inputName: p.inputName, inputType: p.inputType, outputName: p.outputName, name: p.name })),
    connect_function_expressions: bp("mutate", "Wire two expressions inside a MaterialFunction. Params: functionPath, sourceExpression (name or index), sourceOutput?, targetExpression (name or index), targetInput? (#463)", "connect_expressions_in_function", (p) => ({ functionPath: p.functionPath ?? p.materialFunctionPath, sourceExpression: p.sourceExpression, sourceOutput: p.sourceOutput, targetExpression: p.targetExpression, targetInput: p.targetInput })),
    list_function_expressions: bp("read", "List expression nodes inside a MaterialFunction. Params: functionPath (#463)", "list_expressions_in_function", (p) => ({ functionPath: p.functionPath ?? p.materialFunctionPath })),
    build_material:    bp("mutate", "Build a PBR material from a texture set in one call: creates a TextureSample per entry, picks each sampler type FROM THE TEXTURE (a virtual/UDIM texture silently loses its material connection on recompile unless it samples through the Virtual* variant), wires them, recompiles, saves, and reports which connections survived the recompile. Params: name + packagePath? (create) OR materialPath (build into an existing material); textures = {baseColor, normal, roughness, metallic, specular, emissive, opacity, opacityMask, ambientOcclusion, ...} plus packed keys orm (R=AO,G=Roughness,B=Metallic) and rma; samplerTypes? = per-key override (e.g. {normal: 'VirtualNormal'}); clearExisting?; assignToMesh? (StaticMesh or SkeletalMesh asset) with meshSlots? (names or indices, default all) (#946)", "build_material", (p) => ({ name: p.name, packagePath: p.packagePath, materialPath: p.materialPath ?? p.assetPath, textures: p.textures, samplerTypes: p.samplerTypes, clearExisting: p.clearExisting, assignToMesh: p.assignToMesh, meshSlots: p.meshSlots })),
    create_simple:     bp("mutate", "Single-call simple material. Params: name, packagePath?, baseColor? ({r,g,b}), metallic?, specular?, roughness?, emissive?, usages?[] (e.g. InstancedStaticMeshes, Nanite, NiagaraSprites). Recompiles + saves in one shot (#225)", "create_material_simple", (p) => ({ name: p.name, packagePath: p.packagePath, baseColor: p.baseColor, metallic: p.metallic, specular: p.specular, roughness: p.roughness, emissive: p.emissive, usages: p.usages, onConflict: p.onConflict })),
    get_usage:         bp("read", "Read the EMaterialUsage flags on a material. `usages[]` carries every flag this engine build defines with its `enabled` state and the bUsedWith* `propertyName` behind it, and `enabled[]` is just the ones that are on. Pass a material INSTANCE and the flags come from the base material it resolves to, which is the shader map it renders through: `materialPath` names that material and `inherited` is true. Params: assetPath (#1004)", "get_material_usage"),
    set_usage:         bp("mutate", "Turn on EMaterialUsage flag(s) for a material, then recompile and save. Flag names come from this engine own EMaterialUsage reflection, so every usage the build defines is accepted (VolumetricCloud, Voxels, MeshDeformer and the rest included) and `unknown` names only what it truly could not resolve. This only ever turns flags ON: it routes each one through UMaterial::SetMaterialUsage, which is an ensure rather than a write, so a replay also repairs a material whose bit is set but whose shaders were never built. `applied` names the flags this call turned on and `alreadySet` those that were on already. To CLEAR a flag, write its reflected property with editor(set_property): every usage this action recognises is backed by a bUsedWith* UPROPERTY on the material, and the response returns the exact {objectPath, propertyName, value} arguments per flag under `clearCalls`. Clearing a flag does not discard the shader permutations that were compiled for it. Params: assetPath, usage OR usages[] (#225)", "set_material_usage", (p) => ({ assetPath: p.assetPath ?? p.materialPath, usage: p.usage, usages: p.usages })),
    set_shading_model: bp("mutate", "Set shading model. Params: assetPath, shadingModel", "set_material_shading_model"),
    set_blend_mode:    bp("mutate", "Set blend mode. Params: assetPath, blendMode", "set_material_blend_mode"),
    set_domain:        bp("mutate", "Set material domain. Params: assetPath, materialDomain (Surface | DeferredDecal | LightFunction | Volume | PostProcess | UI | RuntimeVirtualTexture). Required for post-process / decal / UI authoring (#299/#356).", "set_material_domain", (p) => ({ assetPath: p.assetPath, materialDomain: p.materialDomain, domain: p.domain })),
    set_base_color:    bp("mutate", "Set base color. Params: assetPath, color", "set_material_base_color"),
    connect_texture:   bp("mutate", "Connect texture to property. Params: materialPath, texturePath, property", "connect_texture_to_material"),
    add_expression:    bp("mutate", "Add expression node. Params: materialPath, expressionType, name?, parameterName?, group?, sortPriority?, defaultValue? (scalar number or {r,g,b,a} for vector params), value? (number for Constant, {r,g,b} for Constant3Vector, {x,y} for Constant2Vector), channels? ({r,g,b,a} bools for ComponentMask), positionX?, positionY? (#318)", "add_material_expression"),
    connect_expressions: bp("mutate", "Wire two expressions. Params: materialPath, sourceExpression, sourceOutput?, targetExpression, targetInput?", "connect_material_expressions"),
    connect_to_property: bp("mutate", "Wire expression to material output. Params: materialPath, expressionName, outputName?, property", "connect_to_material_property"),
    list_expressions:  bp("read", paged("List expression nodes, in the material's own stored order, which is what nodeId indexes into. Params: materialPath"), "list_material_expressions"),
    delete_expression: bp("mutate", "Remove expression. Params: materialPath, expressionName", "delete_material_expression"),
    list_expression_types: bp("read", paged("List available expression types, in the curated order they are grouped in."), "list_expression_types"),
    recompile:         bp("mutate", "Recompile material. Pass recompileChildren=true to cascade to every MaterialInstanceConstant whose parent chain reaches this material (#421). Params: materialPath, recompileChildren?", "recompile_material", (p) => ({ materialPath: p.materialPath, recompileChildren: p.recompileChildren })),
    duplicate:         bp("mutate", "Duplicate material asset. Params: sourcePath, destinationPath", "duplicate_material"),
    validate:          bp("read", "Validate material graph - find orphans, broken refs. Params: assetPath", "validate_material", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    get_shader_stats:  bp("read", "Shader compile stats, sampler+param counts. Params: assetPath", "get_material_shader_stats", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    export_graph:      bp("read", "Export material graph as JSON. Params: assetPath", "export_material_graph", (p) => ({ assetPath: p.assetPath ?? p.materialPath })),
    import_graph:      bp("mutate", "Rebuild graph from JSON. Params: assetPath, nodes, propertyConnections?", "import_material_graph"),
    build_graph:       bp("mutate", "Build graph from spec. Params: assetPath, nodes, propertyConnections?", "build_material_graph"),
    render_preview:    bp("mutate", "Render preview PNG. Params: assetPath, outputPath, width?, height?", "render_material_preview", (p) => ({ assetPath: p.assetPath ?? p.materialPath, outputPath: p.outputPath, width: p.width, height: p.height })),
    begin_transaction: bp("mutate", "Begin undo transaction. Params: label?", "begin_material_transaction"),
    end_transaction:   bp("mutate", "End undo transaction. Params: none", "end_material_transaction"),
    // V15 Runtime Virtual Textures. Every SETTING on an RVT asset, on its
    // volume component and in a landscape's virtual texture group is a
    // UPROPERTY, so asset(set_property) / editor(set_property) already writes
    // all of them and none of these actions is a setter. Each one calls an
    // engine function a property write cannot reach, named in its description.
    create_rvt: bp("mutate", "Create a RuntimeVirtualTexture asset. materialType is validated against RuntimeVirtualTexture::IsMaterialTypeSupported, which is the reason it is a parameter rather than a follow-up property write: a project can disable individual material types to cut shader permutations, and set_property would happily store one that then compiles to nothing. Everything else (tileCount, tileSize, tileBorderSize, compression, adaptive/private/packed page table, continuous update, LOD group) is a plain UPROPERTY: write it with asset(set_property) at the returned objectPath. Reads back the DERIVED layout - size, pageTableSize, layer count and per-layer pixel format and colour space - which no property read produces. Idempotent by path; rollback deletes the asset. Params: name, packagePath? (default /Game/Textures/RVT), materialType? (BaseColor | BaseColor_Normal_Roughness | BaseColor_Normal_Specular | BaseColor_Normal_Specular_YCoCg | BaseColor_Normal_Specular_Mask_YCoCg | Mask4 | WorldHeight | Displacement), onConflict? (skip|error)", "create_runtime_virtual_texture", (p) => ({ name: p.name, packagePath: p.packagePath, materialType: p.materialType, onConflict: p.onConflict })),
    read_rvt: bp("read", "Read a RuntimeVirtualTexture and its whole reference graph: the derived layout (size, pageTableSize, per-layer pixel format, sRGB and YCoCg), every volume bound to it with its transform, every primitive and landscape that writes into it, and every material sample node that reads it. problems[] names the failures that otherwise only show up visually - no volume (so no world bounds), no writer (so every page renders empty), a disabled material type, and the classic one: a sample node whose materialType disagrees with the asset, which decodes the wrong channels and still compiles. level(get_runtime_virtual_texture_summary) answers the level-side question; this answers the asset-side one. Params: rvtPath (assetPath is accepted for it too)", "read_runtime_virtual_texture", (p) => ({ rvtPath: p.rvtPath, assetPath: p.assetPath })),
    add_rvt_volume: bp("mutate", "Spawn the RuntimeVirtualTextureVolume that gives an RVT its world bounds, bind the asset through the engine's SetVirtualTexture (which re-registers the render state, unlike a raw property write), and fit the volume to what actually writes into the texture. An unfitted volume sits at the origin at unit scale and renders a 100cm cube of the world, so the fit is the point. Idempotent BY BINDING rather than by label: two volumes on one RVT is a real misconfiguration (one wins, the other renders nothing) and an existing binding is reported rather than duplicated. When nothing writes into the RVT yet there is nothing to fit to, and the response says so in boundsFitNote rather than reporting a fit that did not happen. Rollback deletes the actor. Params: rvtPath (assetPath is accepted for it too), actorLabel?, boundsMode? (writers|alignActor), boundsAlignActor?", "add_rvt_volume", (p) => ({ rvtPath: p.rvtPath, assetPath: p.assetPath, actorLabel: p.actorLabel, boundsMode: p.boundsMode, boundsAlignActor: p.boundsAlignActor })),
    set_rvt_volume_bounds: bp("mutate", "Refit an RVT volume to the world, which is the Set Bounds button and is not a property write: it DERIVES a transform from what is in the level. boundsMode='writers' covers every primitive whose RuntimeVirtualTextures array names this RVT; boundsMode='alignActor' matches one actor's box and rotation, which is what a landscape wants because the volume's axes have to be the terrain's axes. The volume's own local extent is read back through CalcBounds and solved against the target box rather than assumed to be a unit cube, so the fit survives engine changes. Honest limitation: it does NOT perform the landscape texel snap (that lives in a module the bridge does not link) and says so when bSnapBoundsToLandscape is set. Rollback restores the previous transform exactly. Params: rvtPath? OR actorLabel? OR actorPath?, boundsMode? (writers|alignActor, default writers), boundsAlignActor?", "set_rvt_volume_bounds", (p) => ({ rvtPath: p.rvtPath, assetPath: p.assetPath, actorLabel: p.actorLabel, actorPath: p.actorPath, boundsMode: p.boundsMode, boundsAlignActor: p.boundsAlignActor })),
    add_rvt_sampler: bp("mutate", "Add or rebind the RuntimeVirtualTextureSample node that READS an RVT in a material, then call the engine's InitVirtualTextureDependentSettings, which is the one step add_expression + set_expression_value cannot do: it copies the asset's material type and packed/adaptive page-table flags onto the node and rebuilds its output pins. Setting VirtualTexture alone leaves those stale, which compiles cleanly and decodes the wrong channels. Optionally connects each output pin to the material property of the same name and reports the pins that have no counterpart (WorldHeight, Mask, Mask4, Displacement) rather than dropping them silently. Idempotent by expressionName. MipValueMode, TextureAddressMode and bEnableFeedback stay editor(set_property) territory at the returned expressionObjectPath. Params: materialPath (assetPath is accepted for it too), rvtPath, expressionName?, connectOutputs? (default true), positionX?, positionY?, recompile? (default true)", "add_rvt_sampler", (p) => ({ materialPath: p.materialPath, assetPath: p.assetPath, rvtPath: p.rvtPath, expressionName: p.expressionName, connectOutputs: p.connectOutputs, positionX: p.positionX, positionY: p.positionY, recompile: p.recompile })),
    add_rvt_output: bp("mutate", "Add the RuntimeVirtualTextureOutput node that makes a material WRITE into an RVT, and mirror the material's existing BaseColor / Normal / Roughness / Specular / Opacity connections into it, which by hand is one connect_expressions call per channel with each source expression and output index looked up by eye. Reads the node's inputs by NAME through the same GetInput/GetInputName pair connect_expressions uses, so a channel added by an engine version is picked up rather than mis-wired. Inputs with no material counterpart are reported with the call that wires them. Idempotent by expressionName. Note this does not choose WHICH RVT: that is the primitive's RuntimeVirtualTextures array (assign_rvt_to_landscape, or editor(set_property) on a mesh component). Params: materialPath (assetPath is accepted for it too), expressionName?, mirrorProperties? (default true), positionX?, positionY?, recompile? (default true)", "add_rvt_output", (p) => ({ materialPath: p.materialPath, assetPath: p.assetPath, expressionName: p.expressionName, mirrorProperties: p.mirrorProperties, positionX: p.positionX, positionY: p.positionY, recompile: p.recompile })),
    assign_rvt_to_landscape: bp("mutate", "Assign RVTs to a landscape across EVERY proxy that shares its ULandscapeInfo, not just the actor named. A streaming or World Partition landscape is many ALandscapeStreamingProxy actors, and writing RuntimeVirtualTextures on one of them with set_property leaves the rest rendering nothing into the RVT, which is invisible until the pages come back empty. Also calls PostEditChange plus MarkComponentsRenderStateDirty per proxy, without which the change does not take effect, and checks the two things that make an assignment useless anyway: a landscape material with no RuntimeVirtualTextureOutput node, and an RVT whose material type is disabled for the project. assignMode='set' with an empty list clears the assignment. Rollback replays the named landscape's previous list, with previousPerProxy carrying the exact per-proxy state. Params: actorLabel OR actorPath (the landscape), rvtPaths? (array) OR rvtPath?, assignMode? (set|add|remove, default set)", "assign_rvt_to_landscape", (p) => ({ actorLabel: p.actorLabel, actorPath: p.actorPath, rvtPaths: p.rvtPaths, rvtPath: p.rvtPath, assignMode: p.assignMode })),
    ...epicActions,
  },
  undefined,
  {
    ...epicSchema,
    assetPath: z.string().optional(),
    parameterName: z.string().optional(),
    parameterType: z.string().optional().describe("Parameter type for set_parameter: scalar, vector, texture"),
    expressionIndex: z.number().optional(),
    propertyName: z.string().optional().describe("set_expression_value: name of an arbitrary UPROPERTY on the expression to set via reflection, e.g. SamplerType (#663)"),
    code: z.string().optional().describe("set_custom_expression: HLSL code body (#617)"),
    inputs: z.array(z.string()).optional().describe("set_custom_expression: named input pins (#617)"),
    instances: z.array(z.record(z.unknown())).optional().describe("batch_set_instances: [{assetPath, parentPath?, parameters?}] (#594)"),
    outputType: z.string().optional().describe("set_custom_expression: float1|float2|float3|float4|materialAttributes (#617)"),
    value: z.unknown().optional(),
    parentPath: z.string().optional(),
    newParentPath: z.string().optional().describe("New parent material or material instance path"),
    association: z.string().optional().describe("Material parameter association: Global, Layer, or Blend"),
    parameterIndex: z.number().optional().describe("Material layer/blend parameter index"),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    shadingModel: z.string().optional(),
    blendMode: z.string().optional().describe("Blend mode: Opaque, Masked, Translucent, Additive, Modulate, AlphaComposite, AlphaHoldout"),
    materialDomain: z.string().optional().describe("Material domain for set_domain: Surface, DeferredDecal, LightFunction, Volume, PostProcess, UI, RuntimeVirtualTexture"),
    domain: z.string().optional().describe("Alias for materialDomain"),
    group: z.string().optional().describe("Parameter Group on add_expression for parameter nodes (#318)"),
    sortPriority: z.number().optional().describe("SortPriority within a parameter Group"),
    defaultValue: z.union([z.number(), z.record(z.unknown())]).optional().describe("ScalarParameter default (number) or VectorParameter default ({r,g,b,a})"),
    channels: z.record(z.unknown()).optional().describe("ComponentMask channels {r,g,b,a} bools"),
    positionX: z.number().optional(),
    positionY: z.number().optional(),
    color: Color.optional(),
    materialPath: z.string().optional(),
    recompileChildren: z.boolean().optional().describe("recompile_material: cascade to MaterialInstances whose parent chain reaches this material"),
    texturePath: z.string().optional(),
    property: z.string().optional().describe("Material property: BaseColor, Normal, Roughness, Metallic, EmissiveColor, etc."),
    expressionType: z.string().optional().describe("Expression type: Constant, TextureSample, Multiply, Lerp, ScalarParameter, etc."),
    x: z.number().optional().describe("set_expression_value: a colour/vector component passed at the top level instead of inside `value` (#979)"),
    y: z.number().optional().describe("set_expression_value: a colour/vector component passed at the top level instead of inside `value` (#979)"),
    // The TextureCoordinate branch of set_expression_value reads these three by
    // name. Undeclared, the MCP layer stripped them before the bridge saw them,
    // so the branch could never fire and the call fell through to the generic
    // "no value set" error.
    uTiling: z.number().optional().describe("set_expression_value on a TextureCoordinate node: U tiling multiplier"),
    vTiling: z.number().optional().describe("set_expression_value on a TextureCoordinate node: V tiling multiplier"),
    coordinateIndex: z.number().optional().describe("set_expression_value on a TextureCoordinate node: which UV channel the node reads"),
    sourceExpression: z.string().optional(),
    sourceOutput: z.string().optional(),
    targetExpression: z.string().optional(),
    targetInput: z.string().optional(),
    expressionName: z.string().optional(),
    outputName: z.string().optional(),
    functionPath: z.string().optional().describe("MaterialFunction asset path (#463)"),
    materialFunctionPath: z.string().optional().describe("Alias for functionPath"),
    description: z.string().optional().describe("MaterialFunction description (#463)"),
    inputName: z.string().optional().describe("FunctionInput name (#463)"),
    inputType: z.string().optional().describe("FunctionInput type: Scalar|Vector2|Vector3|Vector4|Texture2D|TextureCube|StaticBool|MaterialAttributes (#463)"),
    sourcePath: z.string().optional(), destinationPath: z.string().optional(),
    outputPath: z.string().optional().describe("Absolute file path for render_preview PNG output"),
    width: z.number().optional(), height: z.number().optional(),
    nodes: z.array(z.record(z.unknown())).optional().describe("Graph spec: [{name,class,posX,posY,...}]"),
    propertyConnections: z.array(z.record(z.unknown())).optional().describe("[{property,from,outputIndex}]"),
    label: z.string().optional().describe("Transaction label"),
    // V15 Runtime Virtual Texture parameters.
    rvtPath: z.string().optional().describe("RuntimeVirtualTexture asset path"),
    recompile: z.boolean().optional().describe("add_rvt_sampler / add_rvt_output: recompile the material after the graph edit (default true)"),
    rvtPaths: z.array(z.string()).optional().describe("assign_rvt_to_landscape: RuntimeVirtualTexture asset paths"),
    materialType: z.string().optional().describe("create_rvt: RVT content layout - BaseColor | BaseColor_Normal_Roughness | BaseColor_Normal_Specular | BaseColor_Normal_Specular_YCoCg | BaseColor_Normal_Specular_Mask_YCoCg | Mask4 | WorldHeight | Displacement"),
    actorLabel: z.string().optional().describe("Editor label of the RVT volume or landscape actor"),
    actorPath: z.string().optional().describe("Full object path of the RVT volume or landscape actor. The unambiguous selector; editor labels are not unique"),
    boundsMode: z.string().optional().describe("add_rvt_volume / set_rvt_volume_bounds: writers (cover every primitive writing into this RVT) | alignActor (match one actor's box and rotation)"),
    boundsAlignActor: z.string().optional().describe("add_rvt_volume / set_rvt_volume_bounds: actor label or object path whose rotation and bounds the volume aligns to, typically the landscape"),
    connectOutputs: z.boolean().optional().describe("add_rvt_sampler: connect each sample output to the material property of the same name (default true)"),
    mirrorProperties: z.boolean().optional().describe("add_rvt_output: mirror the material's own property connections into the RVT output node (default true)"),
    assignMode: z.string().optional().describe("assign_rvt_to_landscape: set (replace the list) | add | remove"),
    baseColor: Color.optional().describe("create_simple base color"),
    metallic: z.number().optional(),
    specular: z.number().optional(),
    roughness: z.number().optional(),
    emissive: z.number().optional(),
    usage: z.string().optional().describe("set_usage: single MATUSAGE flag name"),
    usages: z.array(z.string()).optional().describe("MATUSAGE flag names for create_simple/set_usage (InstancedStaticMeshes, Nanite, VolumetricCloud, ...). get_usage lists every name this engine accepts"),
    onConflict: z.string().optional().describe("create_simple: skip (default) | error"),
    textures: z.record(z.string()).optional().describe("build_material: {materialProperty: textureAssetPath}. Keys: baseColor, normal, roughness, metallic, specular, emissive, opacity, opacityMask, ambientOcclusion, plus packed orm / rma (#946)"),
    samplerTypes: z.record(z.string()).optional().describe("build_material: per-texture EMaterialSamplerType override, e.g. {normal: 'VirtualNormal'}. Omit to let the texture decide (#946)"),
    clearExisting: z.boolean().optional().describe("build_material: delete every existing expression before building (#946)"),
    assignToMesh: z.string().optional().describe("build_material: StaticMesh or SkeletalMesh asset to put the finished material on (#946)"),
    meshSlots: z.array(z.union([z.string(), z.number()])).optional().describe("build_material: mesh material slot names or indices to assign; default every slot (#946)"),
    // cursor + limit for the paged list actions. Declared once: the MCP layer
    // strips a key the category never declares, so a paged action whose
    // category omits these silently returns page one forever.
    ...PAGINATION_SCHEMA,
  },
);
