import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";

export const reflectionTool: ToolDef = categoryTool(
  "reflection",
  "UE reflection: classes, structs, enums, gameplay tags, and SaveGame instances.",
  {
    reflect_class:  bp("Reflect UClass. className accepts the C++ spelling with or without the A/U/F/E prefix (UMyConfig and MyConfig both resolve), a /Script/Module.ClassName path, or a Blueprint class path; a failed lookup lists the spellings tried and the closest matches (#823). Params: className, includeInherited?", "reflect_class"),
    reflect_struct: bp("Reflect UScriptStruct. Params: structName", "reflect_struct"),
    reflect_enum:   bp("Reflect UEnum by full path, short name, or short name without the E prefix. Resolves native enums in any loaded module and loads unloaded Blueprint (UserDefinedEnum) assets via the asset registry. Returns enumPath, userDefined, and per-value name/value/displayName/tooltip; a failed lookup lists close matches (#762). Params: enumName", "reflect_enum"),
    list_classes:   bp("List classes. parentFilter resolves with or without the C++ A/U/F/E prefix (#823). Params: parentFilter?, limit?", "list_classes"),
    list_tags:      bp("List gameplay tags. Params: filter?", "list_gameplay_tags"),
    create_tag:     bp("Create gameplay tag. Params: tag, comment?", "create_gameplay_tag"),
    create_enum:    bp("Create UUserDefinedEnum asset, optionally seeded with entries. Params: name, packagePath?, entries?: (string|{name, displayName?})[], onConflict? (#274)", "create_enum", (p) => ({ name: p.name, packagePath: p.packagePath, entries: p.entries, onConflict: p.onConflict })),
    set_enum_entries: bp("Replace entries on an existing UUserDefinedEnum. Params: assetPath, entries[] (#274)", "set_enum_entries", (p) => ({ assetPath: p.assetPath, entries: p.entries })),
    is_class_loaded: bp("Report whether a UClass is currently loaded in the editor (loaded), whether it exists/is loadable (exists), and its owning module + that module's load state. Distinguishes 'not loaded yet' from 'does not exist'. Params: className (short name, /Script/<Module>.<Class>, or BP class path) (#689)", "is_class_loaded", (p) => ({ className: p.className })),
    is_module_loaded: bp("Report whether a named module is currently loaded. Params: moduleName (#689)", "is_module_loaded", (p) => ({ moduleName: p.moduleName })),
    list_loaded_modules: bp("Enumerate modules with runtime load state. Params: filter? (case-insensitive substring), loadedOnly? (default false). Returns modules[{name, loaded, gameModule}] + totalLoaded/totalModules (#689)", "list_loaded_modules", (p) => ({ filter: p.filter, loadedOnly: p.loadedOnly })),
    inspect_save_game: bp("Load a SaveGame slot read-only and return its reflected UPROPERTY(SaveGame) values. Non-serializable properties are listed in skippedProperties instead of failing the call. Params: slotName, userIndex? (default 0)", "inspect_save_game", (p) => ({ slotName: p.slotName, userIndex: p.userIndex })),
  },
  undefined,
  {
    className: z.string().optional(),
    moduleName: z.string().optional().describe("is_module_loaded: module name (#689)"),
    loadedOnly: z.boolean().optional().describe("list_loaded_modules: only loaded modules (#689)"),
    slotName: z.string().min(1).max(128).optional().describe("inspect_save_game: logical save slot name without a path"),
    userIndex: z.number().int().nonnegative().optional().describe("inspect_save_game: platform user index (default 0)"),
    includeInherited: z.boolean().optional(),
    structName: z.string().optional(),
    enumName: z.string().optional(),
    parentFilter: z.string().optional(),
    limit: z.number().optional(),
    filter: z.string().optional(),
    tag: z.string().optional(),
    comment: z.string().optional(),
    name: z.string().optional().describe("Enum asset name (create_enum)"),
    packagePath: z.string().optional().describe("Package path (default /Game)"),
    assetPath: z.string().optional().describe("Existing UserDefinedEnum path (set_enum_entries)"),
    entries: z.array(z.union([
      z.string(),
      z.object({ name: z.string(), displayName: z.string().optional() }),
    ])).optional().describe("Enum entries - strings or {name, displayName?}"),
    onConflict: z.string().optional().describe("Asset-creation conflict policy: skip (default) | error | overwrite"),
  },
);
