import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { PAGINATION_SCHEMA, paged } from "../pagination.js";
import { actions as epicActions, schema as epicSchema } from "./epic/statetree.generated.js";

export const statetreeTool: ToolDef = categoryTool(
  "statetree",
  "StateTree asset editing: read, modify states/tasks/conditions/transitions/bindings/evaluators/global tasks/colors/state parameters/root parameters, compile and validate.",
  {
    read:                   bp("read", "Full dump of a StateTree asset: state hierarchy (with description, tag, customTickRate, color), tasks, conditions, transitions, evaluators, global tasks, root params, bindings. Params: assetPath", "read_state_tree"),
    list_states:            bp("read", paged("List all states with IDs and paths, depth-first in the tree's authored order. Params: assetPath"), "list_state_tree_states"),
    add_state:              bp("mutate", "Add child state. Params: assetPath, stateId? (parent GUID, omit for root), name, stateType? (State|Group|LinkedAsset|Subtree), selectionBehavior?, insertIndex?", "add_state_tree_state"),
    remove_state:           bp("mutate", "Remove a state by ID. Params: assetPath, stateId", "remove_state_tree_state"),
    set_state_property:     bp("mutate", "Set a property on a state. Params: assetPath, stateId, propertyName (name|type|selectionBehavior|bEnabled|weight|linkedAsset|description|tag|customTickRate|color), value. For tag: gameplay tag string or empty to clear. For customTickRate: number in seconds or empty to disable. For color: palette color display name, GUID, or empty to clear.", "set_state_tree_state_property"),
    clear_state_nodes:      bp("mutate", "Remove all tasks/conditions/transitions from a state. Params: assetPath, stateId", "clear_state_tree_state_nodes"),
    add_task:               bp("mutate", "Add a task to a state. Params: assetPath, stateId, structType (C++ struct name e.g. FMyStateTreeTask or an engine-shipped task like FStateTreeRunParallelStateTreesTask), instanceProperties?", "add_state_tree_task"),
    add_enter_condition:    bp("mutate", "Add an enter condition to a state. Params: assetPath, stateId, structType (C++ struct name), instanceProperties?, operand? (And|Or)", "add_state_tree_enter_condition"),
    remove_enter_condition: bp("mutate", "Remove an enter condition by index. Params: assetPath, stateId, conditionIndex", "remove_state_tree_enter_condition"),
    remove_task:            bp("mutate", "Remove a task by index. Params: assetPath, stateId, taskIndex", "remove_state_tree_task"),
    set_task_instance_property: bp("mutate", "Set a property on a task's instance data. Params: assetPath, stateId, taskIndex, propertyName, value", "set_state_tree_task_instance_property"),
    set_task_property:      bp("mutate", "Set a property on the task's node struct (FStateTreeTaskBase-level: bConsideredForCompletion, bTaskEnabled, bShouldStateChangeOnReselect). Distinct from set_task_instance_property which targets instance data. Params: assetPath, stateId, taskIndex, propertyName, value (string-encoded e.g. 'true'/'false')", "set_state_tree_task_property"),
    add_transition:         bp("mutate", "Add a transition to a state. Params: assetPath, stateId, trigger (OnStateCompleted|OnStateSucceeded|OnStateFailed|OnTick|OnEvent; combine with | e.g. OnStateSucceeded|OnStateFailed), transitionType (GotoState|NextState|Succeeded|Failed), eventTag?, targetStateId?, targetStatePath?, priority? (Low|Normal|Medium|High|Critical), delayDuration?, bDelayTransition?", "add_state_tree_transition"),
    add_transition_condition: bp("mutate", "Add a condition to an existing transition. Params: assetPath, stateId, transitionIndex, structType, instanceProperties?, operand?", "add_state_tree_transition_condition"),
    remove_transition:      bp("mutate", "Remove a transition by index. Params: assetPath, stateId, transitionIndex", "remove_state_tree_transition"),
    add_binding:            bp("mutate", "Add a property binding. Params: assetPath, sourceStructId, sourcePath, targetStructId, targetPath", "add_state_tree_binding"),
    remove_binding:         bp("mutate", "Remove a property binding. Params: assetPath, targetStructId, targetPath", "remove_state_tree_binding"),
    list_bindings:          bp("read", "List all property bindings. Params: assetPath, structId? (filter)", "list_state_tree_bindings"),
    list_bindable_sources:  bp("read", paged("Enumerate the context/bindable sources in a StateTree (context objects, parameters, evaluators, global tasks, per-state nodes) with their structId + struct type - what a property can bind FROM, sorted by structId. Params: assetPath (#681)"), "list_state_tree_bindable_sources", (p) => ({ assetPath: p.assetPath, cursor: p.cursor, limit: p.limit })),
    add_evaluator:          bp("mutate", "Add an evaluator to the StateTree (tree-level). Params: assetPath, structType (must derive from FStateTreeEvaluatorBase), instanceProperties?", "add_state_tree_evaluator"),
    remove_evaluator:       bp("mutate", "Remove an evaluator by node ID. Params: assetPath, nodeId", "remove_state_tree_evaluator"),
    set_evaluator_instance_property: bp("mutate", "Set a property on an evaluator's instance data. Params: assetPath, nodeId, propertyName, value", "set_state_tree_evaluator_instance_property"),
    set_evaluator_property: bp("mutate", "Set a property on the evaluator's node struct (FStateTreeEvaluatorBase-level). Params: assetPath, nodeId, propertyName, value", "set_state_tree_evaluator_property"),
    add_global_task:        bp("mutate", "Add a global task to the StateTree (tree-level). Params: assetPath, structType (must derive from FStateTreeTaskBase), instanceProperties?", "add_state_tree_global_task"),
    remove_global_task:     bp("mutate", "Remove a global task by node ID. Params: assetPath, nodeId", "remove_state_tree_global_task"),
    set_global_task_instance_property: bp("mutate", "Set a property on a global task's instance data. Params: assetPath, nodeId, propertyName, value", "set_state_tree_global_task_instance_property"),
    set_global_task_property: bp("mutate", "Set a property on a global task's node struct (FStateTreeTaskBase-level). Params: assetPath, nodeId, propertyName, value", "set_state_tree_global_task_property"),
    list_colors:            bp("read", "List all color palette entries for a StateTree. Params: assetPath. Returns: colors[] with id, displayName, color.", "list_state_tree_colors"),
    add_color:              bp("mutate", "Add a new color to the StateTree palette. Params: assetPath, displayName, color? (FLinearColor string e.g. '(R=1.0,G=0.0,B=0.0,A=1.0)')", "add_state_tree_color"),
    list_state_parameters:  bp("read", "List parameters defined on a state. Params: assetPath, stateId. Returns: parameters[] with name, id, type, value; also bFixedLayout.", "list_state_tree_state_parameters"),
    add_state_parameter:    bp("mutate", "Add a parameter to a state's property bag. Rejects fixed-layout (linked) states. Params: assetPath, stateId, paramName, paramType (Bool|Int32|Int64|Float|Double|Name|String|Text)", "add_state_tree_state_parameter"),
    remove_state_parameter: bp("mutate", "Remove a parameter from a state's property bag by name. Rejects fixed-layout (linked) states. Params: assetPath, stateId, paramName", "remove_state_tree_state_parameter"),
    set_state_parameter:    bp("mutate", "Set the value of an existing state parameter. On fixed-layout states, also marks the parameter as overridden. Params: assetPath, stateId, paramName, value", "set_state_tree_state_parameter"),
    set_root_parameters:    bp("mutate", "Define root parameters (property bag). Params: assetPath, parameters[] ({name, type}) where type is float|int32|bool|string|name|double", "set_state_tree_root_parameters"),
    set_schema:             bp("mutate", "Attach or replace the StateTree schema, then compile. The schema is what makes a tree compilable: without one the compiler logs \"does not have a schema\" and stops, and everything that loads the asset reports it as failed to link. Repairs a tree that has no editor data at all (what asset(create_asset_by_class) writes) by creating the editor data, the schema and a root state. Omit schema to take StateTreeComponentSchema, then StateTreeAIComponentSchema, then whatever concrete schema this editor has, and read schemaSource / schemaNote to see which was used. Params: assetPath, schema? (/Script/<Module>.<SchemaClass>) (#833)", "set_state_tree_schema", (p) => ({ assetPath: p.assetPath, schema: p.schema })),
    compile:                bp("mutate", "Compile a StateTree asset. Returns success, errors[], warnings[]. Params: assetPath", "compile_state_tree"),
    validate:               bp("read", "Validate a StateTree asset without compiling. Params: assetPath", "validate_state_tree"),
    list_node_types:        bp("read", "Enumerate every task, condition, evaluator and utility consideration THIS tree's schema allows, with the exact structType string add_task / add_enter_condition / add_transition_condition / add_consideration / add_evaluator / add_global_task take, and the property names their instanceProperties map accepts. Every add_* action takes a C++ struct name and nothing listed them, so authoring meant guessing. Also reports the schema's own capability flags (allowEnterConditions, allowUtilityConsiderations, allowEvaluators, allowMultipleTasks, allowGlobalParameters), which is what decides whether an add would be refused, and the context data a binding can come from. Blueprint-authored nodes are listed separately with the wrapper struct and the two calls that author one, because a Blueprint node needs set_node_class after the wrapper is added. Params: assetPath, nodeType? (task|condition|evaluator|consideration|all), filter? (substring on the struct or class name), includeInstanceProperties?, schemaAllowedOnly?", "list_state_tree_node_types"),
    read_state:             bp("read", "Read ONE state whole, including everything the tree-wide read omits: utility considerations, the LinkedSubtree link, RequiredEventToEnter, TasksCompletion, Weight, and every transition's priority, enabled flag, delay variance and reactivation rule. Returns the state's objectPath, which is how the fields with no typed setter are written - editor(set_property) at that path reaches Transitions[0].Priority and the rest. problems[] names the faults a state cannot report about itself: utility selection with no scoring considerations anywhere below it, considerations whose parent never reads them, a Linked type pointing at nothing, and a transition targeting a deleted state. Params: assetPath, stateId OR statePath", "read_state_tree_state"),
    add_consideration:      bp("mutate", "Add a utility consideration to a state, which is what produces the score a parent uses when its selectionBehavior is TrySelectChildrenWithHighestUtility or TrySelectChildrenAtRandomWeightedByUtility. Those behaviours were already settable and nothing could add the scoring half, so the setting could be written and never did anything. Refuses when the tree's schema does not allow considerations, and warns when the PARENT does not select by utility, because that is the silent failure. Params: assetPath, stateId OR statePath, structType, instanceProperties?, operand? (And|Or)", "add_state_tree_consideration"),
    remove_consideration:   bp("mutate", "Remove a utility consideration from a state by index. The rollback captures the struct type, operand and instance values, and says plainly that a replay appends at the end with a new nodeId rather than restoring its position or its bindings. Params: assetPath, stateId OR statePath, considerationIndex", "remove_state_tree_consideration"),
    remove_transition_condition: bp("mutate", "Remove one condition from a transition by index. add_transition_condition shipped without it, so a mistyped condition could only be undone by deleting the whole transition. Params: assetPath, stateId OR statePath, transitionIndex, conditionIndex", "remove_state_tree_transition_condition"),
    set_state_link:         bp("mutate", "Link a state to a Subtree state in THIS asset, or to another StateTree asset, or clear both. UStateTreeState carries two separate link fields and only the asset one had any route: add_state documented a linkedSubtree parameter and assigned LinkedAsset with it, so in-asset subtree reuse was impossible. Goes through SetLinkedState / SetLinkedStateAsset rather than assigning the field, which is what pulls the linked target's parameters into this state - without that a linked state has an empty fixed-layout parameter list and set_state_parameter has nothing to override. Params: assetPath, stateId OR statePath, linkType (subtree|asset|none), targetStateId? OR targetStatePath? (for subtree), linkedAsset? (for asset)", "set_state_tree_state_link"),
    move_state:             bp("mutate", "Reparent or reorder an existing state. add_state takes an insertIndex for a NEW state and nothing could move one afterwards, so wrong order meant delete and rebuild - and order is load-bearing, since TrySelectChildrenInOrder walks it and NextState and NextSelectableState transitions resolve through it. Refuses to move a state under its own descendant, which would detach the branch. insertIndex is the final position among siblings; omit it to append. Reports unchanged when the state is already there, and rolls back to its previous parent and index. Params: assetPath, stateId OR statePath, newParentStateId? OR newParentStatePath? OR toRoot?, insertIndex?", "move_state_tree_state"),
    set_node_class:         bp("mutate", "Point a Blueprint node wrapper at its Blueprint class AND reallocate its instance data. This is the step with no property-write equivalent: the wrapper reports the Blueprint class AS its instance data type, so a node added before the class is set has no instance data at all, and writing the class afterwards does not go back and allocate it. Works on any task, condition, transition condition, consideration, evaluator or global task, addressed by the nodeId every add_* action returns. Returns instanceObjectPath, where the Blueprint's own variables live for editor(set_property). Params: assetPath, nodeId, nodeClass", "set_state_tree_node_class"),
    read_runtime:           bp("read", "Read a RUNNING StateTree in depth: run status, last tick status, the state change count, the active states, the execution frames and the pending event queue. gameplay(get_state_tree_runtime) answers the same question with active state names only, which cannot tell you whether the tree succeeded, failed or stopped, nor whether an event you sent is still waiting to be consumed. Needs a game world, so run it in PIE. Params: actorLabel OR actorPath, componentName?, world? (pie|auto|editor), pieInstance?, includeDebugStrings?", "read_state_tree_runtime"),
    send_event:             bp("mutate", "Send a gameplay event to a running StateTree, which is how an event-driven tree is meant to be driven from outside and had no route at all. The event is QUEUED and consumed on the tree's next tick, so the snapshot returned still shows the state before it is handled; read it again with read_runtime after a tick. Refuses an unregistered tag, since no transition could ever match one. Has no inverse: once queued it is consumed and whatever it triggered has run. Params: actorLabel OR actorPath, eventTag, componentName?, origin?, world? (pie|auto|editor), pieInstance?", "send_state_tree_event"),
    request_transition:     bp("mutate", "Force a running StateTree to transition to a named state, resolved through the COMPILED data - so a state added since the last compile is reported as missing rather than silently ignored. Queued like an event and resolved on the next tick against every other pending request by priority. Refuses when the tree is not Running, naming the status it is in. targetStateTag needs UE 5.8 or later; targetStateId works everywhere. Params: actorLabel OR actorPath, targetStateId OR targetStateTag, priority? (Low|Normal|Medium|High|Critical), fallback? (None|NextSelectableSibling), componentName?, world? (pie|auto|editor), pieInstance?", "request_state_tree_transition"),
    ...epicActions,
  },
  undefined,
  {
    ...epicSchema,
    assetPath: z.string().describe("StateTree asset path, e.g. /Game/Path/To/ST_Asset"),
    schema: z.string().optional().describe("set_schema: StateTree schema class path, e.g. /Script/GameplayStateTreeModule.StateTreeComponentSchema (#833)"),
    stateId: z.string().optional().describe("GUID of the target state (or parent state for add_state)"),
    statePath: z.string().optional().describe("Dot-path to state as alternative to stateId"),
    name: z.string().optional().describe("Name for a new state"),
    stateType: z.string().optional().describe("State type: State, Group, LinkedAsset, Subtree"),
    selectionBehavior: z.string().optional().describe("Selection behavior: TryEnterState, TrySelectChildrenInOrder, TrySelectChildrenAtRandom, etc."),
    insertIndex: z.number().optional().describe("Insert position for add_state"),
    propertyName: z.string().optional().describe("Property name for set_state_property / set_task_instance_property / set_evaluator_instance_property / set_global_task_instance_property"),
    value: z.string().optional().describe("Property value to set (as string)"),
    structType: z.string().optional().describe("C++ struct name for tasks/conditions/evaluators, e.g. FMyStateTreeTask"),
    instanceProperties: z.record(z.unknown()).optional().describe("Key-value map of instance data properties to set on new tasks/conditions/evaluators/global tasks"),
    operand: z.string().optional().describe("Expression operand for conditions: And or Or"),
    taskIndex: z.number().optional().describe("Task index within the state for remove/set operations"),
    conditionIndex: z.number().optional().describe("Enter condition index for remove_enter_condition"),
    trigger: z.string().optional().describe("Transition trigger: OnStateCompleted, OnStateSucceeded, OnStateFailed, OnTick, OnEvent"),
    transitionType: z.string().optional().describe("Transition type: GotoState, NextState, Succeeded, Failed, NextSelectableState"),
    eventTag: z.string().optional().describe("Gameplay tag for OnEvent transitions, e.g. MyGame.SomeEvent"),
    targetStateId: z.string().optional().describe("Target state GUID for GotoState transitions"),
    targetStatePath: z.string().optional().describe("Target state dot-path for GotoState transitions"),
    priority: z.string().optional().describe("Transition priority: Low, Normal, Medium, High, Critical"),
    delayDuration: z.number().optional().describe("Transition delay in seconds"),
    bDelayTransition: z.boolean().optional().describe("Enable transition delay"),
    transitionIndex: z.number().optional().describe("Transition index for remove/condition operations"),
    sourceStructId: z.string().optional().describe("Source struct GUID for bindings"),
    sourcePath: z.string().optional().describe("Source property path for bindings"),
    targetStructId: z.string().optional().describe("Target struct GUID for bindings"),
    targetPath: z.string().optional().describe("Target property path for bindings"),
    structId: z.string().optional().describe("Filter bindings by struct GUID"),
    nodeId: z.string().optional().describe("GUID of an evaluator or global task node (for remove/set_*_property operations)"),
    displayName: z.string().optional().describe("Display name for a new color palette entry"),
    color: z.string().optional().describe("FLinearColor string e.g. '(R=1.0,G=0.0,B=0.0,A=1.0)' for add_color"),
    paramName: z.string().optional().describe("Parameter name for state parameter operations"),
    paramType: z.string().optional().describe("Parameter type for add_state_parameter: Bool, Int32, Int64, Float, Double, Name, String, Text"),
    parameters: z.array(z.object({
      name: z.string(),
      type: z.string(),
    })).optional().describe("Root parameter definitions: [{name, type}] where type is float, int32, bool, string, name, double"),
    linkedSubtree: z.string().optional().describe("add_state: StateTree ASSET path assigned to LinkedAsset. To link to a Subtree state inside THIS asset, use set_state_link with linkType=\"subtree\" - that is a different field and this parameter never reached it."),

    // Node type discovery (V8).
    nodeType: z.string().optional().describe("list_node_types: task, condition, evaluator, consideration, or all (default)."),
    filter: z.string().optional().describe("list_node_types: return only structs and classes whose name contains this substring."),
    includeInstanceProperties: z.boolean().optional().describe("list_node_types: include each node type's instance-data property list, which names the keys instanceProperties accepts (default true)."),
    schemaAllowedOnly: z.boolean().optional().describe("list_node_types: return only node types this tree's schema permits (default true). false lists everything the engine has loaded, including ones an add would refuse."),

    // Considerations, links, moves and Blueprint node classes (V8).
    considerationIndex: z.number().optional().describe("remove_consideration: index of the consideration within the state, as read_state reports it."),
    linkType: z.string().optional().describe("set_state_link: subtree (a Subtree state in this asset), asset (another StateTree asset), or none (clear both)."),
    linkedAsset: z.string().optional().describe("set_state_link with linkType=\"asset\": the StateTree asset this state runs."),
    toRoot: z.boolean().optional().describe("move_state: move the state to the top level of the asset instead of under a parent."),
    newParentStateId: z.string().optional().describe("move_state: GUID of the state to move under."),
    newParentStatePath: z.string().optional().describe("move_state: dot-path of the state to move under, as an alternative to newParentStateId."),
    nodeClass: z.string().optional().describe("set_node_class: the Blueprint class this node runs, as a class path or a loaded class name."),

    // Runtime (V8). A StateTree only runs in a game world, so these need PIE.
    actorLabel: z.string().optional().describe("Editor label of the actor carrying the running StateTree component."),
    actorPath: z.string().optional().describe("Full object path of the actor carrying the running StateTree component; unambiguous where a label is not."),
    componentName: z.string().optional().describe("Which StateTree component to address when the actor has more than one."),
    world: z.string().optional().describe("Which world to look in: pie (default for the runtime actions), auto, or editor."),
    pieInstance: z.number().optional().describe("Which PIE instance to address when several are running."),
    includeDebugStrings: z.boolean().optional().describe("read_runtime: include the engine's own debug dump of the execution state."),
    origin: z.string().optional().describe("send_event: who the event says it came from (default \"ue-mcp\"), which a task can read to tell external events from in-tree ones."),
    targetStateTag: z.string().optional().describe("request_transition: the Tag of the state to transition to, as an alternative to targetStateId. UE 5.8 and later."),
    fallback: z.string().optional().describe("request_transition: None (default) or NextSelectableSibling, which is tried when the target state cannot be selected."),
    // cursor + limit for the paged list actions. Declared once: the MCP layer
    // strips a key the category never declares, so a paged action whose
    // category omits these silently returns page one forever.
    ...PAGINATION_SCHEMA,
  },
);
