import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";

export const widgetTool: ToolDef = categoryTool(
  "widget",
  "UMG Widget Blueprints, Editor Utility Widgets, and Editor Utility Blueprints.",
  {
    read_tree:         bp("Read widget hierarchy. Params: assetPath", "read_widget_tree"),
    get_details:       bp("Inspect widget (curated subset). Params: assetPath, widgetName", "get_widget_details"),
    get_properties:    bp("Full reflected property dump for a widget - every UPROPERTY (RenderOpacity, Visibility, ColorAndOpacity, Border padding/colors, Image brush TintColor/ImageSize, fonts, etc.) plus the slot block, for diagnosing visual bugs get_details omits. Pass includeSubtree to also dump children (#547). Params: assetPath, widgetName, includeSubtree?", "get_widget_properties", (p) => ({ assetPath: p.assetPath, widgetName: p.widgetName, includeSubtree: p.includeSubtree })),
    list_bindings:     bp("List designer property bindings on a WidgetBlueprint (the UE 5.7 Python API keeps them protected). Returns {widgetName, propertyName, functionName, bindingType}. Optional filterWidgetName/filterProperty (#530). Params: assetPath, filterWidgetName?, filterProperty?", "list_widget_bindings", (p) => ({ assetPath: p.assetPath, filterWidgetName: p.filterWidgetName, filterProperty: p.filterProperty })),
    clear_binding:     bp("Remove designer binding(s) matching widgetName (and optional propertyName) from a WidgetBlueprint without opening the editor. Idempotent (#530). Params: assetPath, widgetName, propertyName?", "clear_widget_binding", (p) => ({ assetPath: p.assetPath, widgetName: p.widgetName, propertyName: p.propertyName })),
    set_property:      bp("Set widget property. Slot struct props take UE struct text that persists every field - `Slot.Size`=`(Value=1.0,SizeRule=Fill)`, `Slot.Padding`=`(Left=8,Top=8,Right=8,Bottom=8)` - or a nested field path like `Slot.Size.Value` / `Slot.Padding.Left`; an invalid value errors instead of silently writing 0 (#532). Params: assetPath, widgetName, propertyName, value", "set_widget_property"),
    list:              bp("List Widget BPs. Params: directory?, recursive?", "list_widget_blueprints"),
    read_animations:   bp("Read UMG animations. Params: assetPath", "read_widget_animations"),
    create:            bp("Create Widget BP. Params: name, packagePath?, parentClass?", "create_widget_blueprint"),
    create_utility_widget:    bp("Create editor utility widget. Params: name, packagePath?", "create_editor_utility_widget"),
    run_utility_widget:       bp("Open editor utility widget. Params: assetPath", "run_editor_utility_widget"),
    create_utility_blueprint: bp("Create editor utility blueprint. Params: name, packagePath?", "create_editor_utility_blueprint"),
    run_utility_blueprint:    bp("Run editor utility blueprint. Params: assetPath", "run_editor_utility_blueprint"),
    add_widget:               bp("Add widget to widget tree. Params: assetPath, widgetClass, widgetName?, parentWidgetName?", "add_widget"),
    remove_widget:            bp("Remove widget from tree. Params: assetPath, widgetName", "remove_widget"),
    move_widget:              bp("Reparent widget. Params: assetPath, widgetName, newParentWidgetName", "move_widget"),
    set_root:                 bp("Replace WBP root with an existing widget by name (#365). Params: assetPath, widgetName", "set_root_widget", (p) => ({ assetPath: p.assetPath, path: p.path, widgetName: p.widgetName })),
    wrap_root:                bp("Wrap the current root in a new panel widget (UMG 'Wrap With'). Params: assetPath, wrapperClass (must be a UPanelWidget subclass), wrapperName? (#365)", "wrap_root_widget", (p) => ({ assetPath: p.assetPath, path: p.path, wrapperClass: p.wrapperClass, widgetClass: p.widgetClass, wrapperName: p.wrapperName })),
    list_classes:             bp("List available widget classes", "list_widget_classes"),
    list_runtime:             bp("(#160) List live UUserWidget instances in the PIE world. Params: classFilter?, namePrefix?, viewportOnly?", "list_runtime_widgets"),
    get_runtime:              bp("(#160) Inspect a live PIE widget tree with text/visibility/brush/percent values. Params: widgetName? | className?, childName?, maxDepth?", "get_runtime_widget"),
    get_runtime_delegates:    bp("(#161) Read delegate binding state on a live PIE widget. Params: widgetName, className?. Returns array of {delegateName, isBound, numBindings}", "get_runtime_delegates"),
  },
  undefined,
  {
    assetPath: z.string().optional(),
    widgetName: z.string().optional(),
    includeSubtree: z.boolean().optional().describe("get_properties: also dump descendant widgets (#547)"),
    widgetClass: z.string().optional(),
    parentWidgetName: z.string().optional(),
    newParentWidgetName: z.string().optional(),
    propertyName: z.string().optional(),
    filterWidgetName: z.string().optional().describe("list_bindings: only bindings on this widget (#530)"),
    filterProperty: z.string().optional().describe("list_bindings: only bindings of this property (#530)"),
    value: z.unknown().optional(),
    directory: z.string().optional(),
    recursive: z.boolean().optional(),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    parentClass: z.string().optional(),
    classFilter: z.string().optional().describe("Class name substring filter for list_runtime"),
    className: z.string().optional().describe("Widget class name for get_runtime (first match wins)"),
    namePrefix: z.string().optional().describe("Instance name prefix filter for list_runtime"),
    viewportOnly: z.boolean().optional().describe("list_runtime: only return widgets currently added to the viewport"),
    childName: z.string().optional().describe("get_runtime: restrict the tree walk to the named child inside the UserWidget"),
    maxDepth: z.number().optional().describe("get_runtime: max widget-tree depth to walk (default 6)"),
    wrapperClass: z.string().optional().describe("wrap_root: panel widget class (CanvasPanel, VerticalBox, Overlay, etc.)"),
    wrapperName: z.string().optional().describe("wrap_root: optional name for the new wrapper widget"),
    path: z.string().optional().describe("Alias for assetPath"),
  },
);
