import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { normalizeWidgetParams } from "./widget-params.js";

export const widgetTool: ToolDef = categoryTool(
  "widget",
  "UMG Widget Blueprints, Editor Utility Widgets, and Editor Utility Blueprints. One parameter contract across every action (#798): the asset is always `assetPath`, an Unreal package path such as `/Game/UI/WBP_Example`; a widget inside the tree is always `widgetName`; its parent panel is always `parentWidgetName`; arguments for the `epic_*` actions always go in `input`, and a top-level `assetPath` is folded into the asset reference of the wrapped tool for you. A `.uasset` suffix, an object suffix (`.WBP_Example`), backslashes, and the legacy `path` / `widgetBlueprintPath` / `widgetBlueprint` spellings are accepted and normalized. Create actions take `assetPath` too; `name` plus `packagePath` remains valid and is composed into it. See [Widget parameter contract](widget-parameters.md).",
  {
    read_tree:         bp("Read widget hierarchy. Params: assetPath", "read_widget_tree"),
    get_details:       bp("Inspect widget (curated subset). Params: assetPath, widgetName", "get_widget_details"),
    get_properties:    bp("Full reflected property dump for a widget - every UPROPERTY (RenderOpacity, Visibility, ColorAndOpacity, Border padding/colors, Image brush TintColor/ImageSize, fonts, etc.) plus the slot block, for diagnosing visual bugs get_details omits. Pass includeSubtree to also dump children (#547). Params: assetPath, widgetName, includeSubtree?", "get_widget_properties", (p) => ({ assetPath: p.assetPath, widgetName: p.widgetName, includeSubtree: p.includeSubtree })),
    list_bindings:     bp("List designer property bindings on a WidgetBlueprint (the UE 5.7 Python API keeps them protected). Returns {widgetName, propertyName, functionName, bindingType}. Optional filterWidgetName/filterProperty (#530). Params: assetPath, filterWidgetName?, filterProperty?", "list_widget_bindings", (p) => ({ assetPath: p.assetPath, filterWidgetName: p.filterWidgetName, filterProperty: p.filterProperty })),
    clear_binding:     bp("Remove designer binding(s) matching widgetName (and optional propertyName) from a WidgetBlueprint without opening the editor. Idempotent (#530). Params: assetPath, widgetName, propertyName?", "clear_widget_binding", (p) => ({ assetPath: p.assetPath, widgetName: p.widgetName, propertyName: p.propertyName })),
    set_property:      bp("Set widget property. Slot struct props take UE struct text that persists every field - `Slot.Size`=`(Value=1.0,SizeRule=Fill)`, `Slot.Padding`=`(Left=8,Top=8,Right=8,Bottom=8)` - or a nested field path like `Slot.Size.Value` / `Slot.Padding.Left`; an invalid value errors instead of silently writing 0 (#532). Params: assetPath, widgetName, propertyName, value", "set_widget_property"),
    set_style:         bp("Set a full/nested style struct on a widget from JSON (FButtonStyle, FEditableTextBoxStyle, FSlateFontInfo, FSlateColor and their nested brushes) - what set_property's scalar path can't express. value is a JSON object mirroring the struct. Params: assetPath, widgetName, propertyName (e.g. WidgetStyle), value (#563)", "set_widget_style", (p) => ({ assetPath: p.assetPath, widgetName: p.widgetName, propertyName: p.propertyName, value: p.value })),
    reorder_child:     bp("Reorder a widget among its parent panel's children (move to a sibling index) - e.g. insert a new row BETWEEN two existing children. move_widget only reparents. Params: assetPath, widgetName, index (#635)", "reorder_child", (p) => ({ assetPath: p.assetPath, widgetName: p.widgetName, index: p.index })),
    bulk_set_properties: bp("Apply many {widgetName, propertyName, value} style/property writes to a WidgetBlueprint in one call (single compile+save) - font/color/style stylesheet across many widgets. Params: assetPath, properties[] (#563)", "bulk_set_widget_properties", (p) => ({ assetPath: p.assetPath, properties: p.properties })),
    list:              bp("List Widget BPs. Params: directory?, recursive?", "list_widget_blueprints"),
    read_animations:   bp("Read UMG animations. Params: assetPath", "read_widget_animations"),
    create:            bp("Create Widget BP. assetPath is the full destination, e.g. /Game/UI/WBP_Example; name + packagePath is the older spelling of the same thing and is composed into it. Params: assetPath, name?, packagePath?, parentClass?", "create_widget_blueprint"),
    create_utility_widget:    bp("Create editor utility widget. Params: assetPath, name?, packagePath?", "create_editor_utility_widget"),
    run_utility_widget:       bp("Open editor utility widget. Params: assetPath", "run_editor_utility_widget"),
    create_utility_blueprint: bp("Create editor utility blueprint. Params: assetPath, name?, packagePath?", "create_editor_utility_blueprint"),
    run_utility_blueprint:    bp("Run editor utility blueprint. Params: assetPath", "run_editor_utility_blueprint"),
    // #799: both compile and save the Widget Blueprint before they answer, and
    // that can run well past the 30s default when the asset is open in the
    // designer. The mutation is on disk by the time the default cap expires, so
    // giving up early only turns a completed call into an ambiguous one. Both
    // are idempotent by assetPath + widgetName, so a retry is safe.
    add_widget: {
      ...bp("Add widget to widget tree. Idempotent by assetPath + widgetName: passing widgetName makes a retry safe, and the result carries requestedWidgetName/persistedWidgetName/renamed plus compileStatus. Params: assetPath, widgetClass, widgetName?, parentWidgetName?", "add_widget"),
      timeoutMs: 120_000,
    },
    remove_widget: {
      ...bp("Remove widget from tree. Idempotent, and clears the widget's Widget Blueprint GUID metadata so later compiles stop reporting a deleted variable (#799). Params: assetPath, widgetName", "remove_widget"),
      timeoutMs: 120_000,
    },
    move_widget:              bp("Reparent widget. Params: assetPath, widgetName, newParentWidgetName", "move_widget"),
    set_root:                 bp("Replace WBP root with an existing widget by name (#365). Params: assetPath, widgetName", "set_root_widget", (p) => ({ assetPath: p.assetPath, widgetName: p.widgetName })),
    wrap_root:                bp("Wrap the current root in a new panel widget (UMG 'Wrap With'). Params: assetPath, wrapperClass (must be a UPanelWidget subclass), wrapperName? (#365)", "wrap_root_widget", (p) => ({ assetPath: p.assetPath, wrapperClass: p.wrapperClass, widgetClass: p.widgetClass, wrapperName: p.wrapperName })),
    list_classes:             bp("List available widget classes", "list_widget_classes"),
    extract_subtree:          bp("Lift an authored designer subtree out of one WidgetBlueprint into a standalone one, using UMG's own clipboard serializer so hierarchy, child order, editable properties, panel slot data and named-slot content survive. The selected widget becomes the destination root. dryRun defaults to true and only returns the name mapping - pass dryRun=false to actually write the asset. The destination must be absent or empty; an exact-shape replay returns existed. The source is never compiled or saved. Params: sourceAssetPath, sourceWidgetName, destinationAssetPath, destinationParentClass?, destinationRootName?, dryRun?", "extract_widget_subtree", (p) => ({ sourceAssetPath: p.sourceAssetPath, sourceWidgetName: p.sourceWidgetName, destinationAssetPath: p.destinationAssetPath, destinationParentClass: p.destinationParentClass, destinationRootName: p.destinationRootName, dryRun: p.dryRun })),
    list_runtime:             bp("(#160) List live UUserWidget instances in the PIE world. Params: classFilter?, namePrefix?, viewportOnly?", "list_runtime_widgets"),
    get_runtime:              bp("(#160) Inspect a live PIE widget tree with text/visibility/brush/percent plus style values: renderOpacity (all), colorAndOpacity (TextBlock/Image), Border brushColor/contentColorAndOpacity (#592). includeLayout adds read-only layout diagnostics to every node - geometry (desired/local/absolute size, layout and render bounds), render transform, effective opacity, reflected slot properties including structured Canvas anchors/offsets/alignment, derived clipping, parent and viewport overlap, and a diagnostics array - plus the host UserWidget node under `host`, a `layoutCapture` summary, and per-node `deltaSincePreviousCapture` against the previous includeLayout call on that instance, so capture / reproduce / capture again isolates position-dependent sizing. Off by default: it is a much larger payload. Params: widgetName? | className?, childName?, maxDepth?, includeLayout?", "get_runtime_widget"),
    inspect_runtime_instances: bp("Inspect every matching live widget instance (never an implicit first match), with stable identity/owning-player metadata and selected reflected properties on the widget or subtree. Requires a running PIE/Game world and errors instead of falling back to the editor world. Passing childName or childClassFilter implies includeSubtree. Provide widgetName or classFilter. Params: widgetName?, classFilter?, propertyNames[]?, includeSubtree?, childName?, childClassFilter?, viewportOnly?, world?, pieInstance?, maxInstances?, maxNodesPerInstance?", "inspect_runtime_instances", (p) => ({ widgetName: p.widgetName, classFilter: p.classFilter, propertyNames: p.propertyNames, includeSubtree: p.includeSubtree, childName: p.childName, childClassFilter: p.childClassFilter, viewportOnly: p.viewportOnly, world: p.world, pieInstance: p.pieInstance, maxInstances: p.maxInstances, maxNodesPerInstance: p.maxNodesPerInstance })),
    get_runtime_delegates:    bp("(#161) Read delegate binding state on a live PIE widget. Params: widgetName, className?. Returns array of {delegateName, isBound, numBindings}", "get_runtime_delegates"),
    add_to_viewport:          bp("(#602) Instantiate a WidgetBlueprint and add it to the live PIE viewport for visual verification. Requires PIE running. Params: assetPath (WidgetBlueprint path), zOrder?", "add_to_viewport", (p) => ({ assetPath: p.assetPath, zOrder: p.zOrder })),
    invoke_runtime_function:  bp("(#559/#812) Fire a UI interaction on a live PIE widget: a parameterless UFUNCTION (functionName) on the located UserWidget, OR drive an interactive child via childName - Button (click), CheckBox (value true/false/toggle), Slider and SpinBox (numeric value), EditableText/EditableTextBox/MultiLineEditableText/MultiLineEditableTextBox (string value), ComboBoxString (option string or index). The matching delegate is broadcast so bound Blueprint logic runs. functionName alongside childName picks the delegate (e.g. OnPressed, OnTextChanged). Locate the widget with widgetName or className. Params: widgetName?|className?, functionName?, childName?, value?, commitMethod?", "invoke_runtime_function", (p) => ({ widgetName: p.widgetName, className: p.className, functionName: p.functionName, childName: p.childName, value: p.value, commitMethod: p.commitMethod })),
  },
  undefined,
  {
    assetPath: z.string().optional().describe("Canonical Widget Blueprint / Editor Utility asset path, e.g. /Game/UI/WBP_Example (#798)"),
    widgetName: z.string().optional().describe("Canonical name of a widget inside the tree (#798)"),
    includeSubtree: z.boolean().optional().describe("get_properties/inspect_runtime_instances: also dump descendant widgets (#547)"),
    widgetClass: z.string().optional(),
    parentWidgetName: z.string().optional().describe("Canonical name of the parent panel widget (#798)"),
    newParentWidgetName: z.string().optional(),
    propertyName: z.string().optional(),
    filterWidgetName: z.string().optional().describe("list_bindings: only bindings on this widget (#530)"),
    filterProperty: z.string().optional().describe("list_bindings: only bindings of this property (#530)"),
    value: z.unknown().optional(),
    properties: z.array(z.record(z.unknown())).optional().describe("bulk_set_properties: [{widgetName, propertyName, value}] (#563)"),
    index: z.number().optional().describe("reorder_child: target sibling index within the parent panel (#635)"),
    directory: z.string().optional(),
    recursive: z.boolean().optional(),
    name: z.string().optional().describe("create actions: bare asset name, used with packagePath. assetPath is the canonical alternative (#798)"),
    packagePath: z.string().optional().describe("create actions: destination folder, used with name (#798)"),
    parentClass: z.string().optional(),
    classFilter: z.string().optional().describe("Class name substring filter for runtime widget queries"),
    propertyNames: z.array(z.string()).optional().describe("inspect_runtime_instances: exact reflected property names to serialize"),
    childClassFilter: z.string().optional().describe("inspect_runtime_instances: class substring filter for subtree nodes (implies includeSubtree)"),
    world: z.enum(["pie", "game", "auto"]).optional().describe("inspect_runtime_instances: runtime world scope (default pie). The editor world is never a valid target"),
    pieInstance: z.number().int().optional().describe("inspect_runtime_instances: PIE instance id for multi-client sessions"),
    maxInstances: z.number().int().min(1).max(500).optional().describe("inspect_runtime_instances: maximum matching widget instances returned"),
    maxNodesPerInstance: z.number().int().min(1).max(2000).optional().describe("inspect_runtime_instances: maximum root/subtree nodes per instance"),
    className: z.string().optional().describe("Widget class name for get_runtime (first match wins)"),
    namePrefix: z.string().optional().describe("Instance name prefix filter for list_runtime"),
    viewportOnly: z.boolean().optional().describe("list_runtime/inspect_runtime_instances: only return widgets currently added to the viewport"),
    childName: z.string().optional().describe("get_runtime/invoke_runtime_function/inspect_runtime_instances: named child inside the UserWidget (#559)"),
    functionName: z.string().optional().describe("invoke_runtime_function: parameterless UFUNCTION to call on the live widget (#559), or with childName the child delegate to fire (#812)"),
    commitMethod: z.string().optional().describe("invoke_runtime_function: text/spin box commit type - OnEnter (default), OnUserMovedFocus, OnCleared, Default (#812)"),
    zOrder: z.number().optional().describe("add_to_viewport: viewport Z-order (#602)"),
    maxDepth: z.number().optional().describe("get_runtime: max widget-tree depth to walk (default 6)"),
    includeLayout: z.boolean().optional().describe("get_runtime: add read-only layout diagnostics (geometry, slot, clipping, viewport, per-node deltas) to every node and report the host UserWidget under `host` (#775)"),
    wrapperClass: z.string().optional().describe("wrap_root: panel widget class (CanvasPanel, VerticalBox, Overlay, etc.)"),
    wrapperName: z.string().optional().describe("wrap_root: optional name for the new wrapper widget"),
    // Accepted spellings of the canonical names above. Declared so the
    // transport does not strip them before the normalizer can fold them in.
    path: z.string().optional().describe("Legacy alias for assetPath. Use assetPath (#798)"),
    widgetBlueprintPath: z.string().optional().describe("Alias for assetPath. Use assetPath (#798)"),
    widgetBlueprint: z.union([z.string(), z.record(z.unknown())]).optional().describe("Alias for assetPath, also accepted as the engine's {refPath} object reference. Use assetPath (#798)"),
    widgetDisplayName: z.string().optional().describe("Alias for widgetName. Use widgetName (#798)"),
    parentWidget: z.string().optional().describe("Alias for parentWidgetName. Use parentWidgetName (#798)"),
    sourceAssetPath: z.string().optional().describe("extract_subtree: WidgetBlueprint the subtree is read from"),
    sourceWidgetName: z.string().optional().describe("extract_subtree: widget in the source that becomes the extracted root"),
    destinationAssetPath: z.string().optional().describe("extract_subtree: destination package path, including the new asset name"),
    destinationParentClass: z.string().optional().describe("extract_subtree: UUserWidget subclass for the destination (default UserWidget)"),
    destinationRootName: z.string().optional().describe("extract_subtree: name override for the extracted root; descendants keep their names"),
    dryRun: z.boolean().optional().describe("extract_subtree: plan only, no asset is created or saved (default true)"),
  },
  { normalizeParams: normalizeWidgetParams },
);
